### ISSUE TITLE
Implementing an event generates parent node overlapping event node

### ISSUE THREAD

**Issue by geordiemhall** [fpwong/BlueprintAssistWiki#100]
Not sure if this is because I have 'never auto-format' turned on, but if I just right-click in a blank actor, and select `Event Tick`, it adds a call to the parent function (as desired), but totally overlapping the original event.

![image](https://user-images.githubusercontent.com/3511383/202377598-98ec5d1a-ebc7-4c49-9078-66e7f05b1fe7.png)

As a user I'd kind of expect the parent call to still be 'auto formatted' even if that's turned off, since it's actually an extra node that's inserted by BA. eg. just putting it a little to the right of the original would be fine, even if it doesn't obey the final spacing rules until I next format the graph properly.

**Comment by fpwong** [comment]
Ah this is definitely something I've overlooked. Since adding the parent function node only ever occurs when there is 1 event node, I think a safe solution is to simply always run the formatting afterwards. This will be included in the next update.

**Comment by geordiemhall** [comment]
Thanks!

**Comment by fpwong** [comment]
This should be fixed in 4.0.9
