### ISSUE TITLE
Ctrl+D is now "Duplicate" in UE 5, should not disconnect

### ISSUE THREAD

**Issue by sinbad** [fpwong/BlueprintAssistWiki#102]
UE5 changed the default keyboard shortcut for "Duplicate selected" from Ctrl+W to Ctrl+D (more standard). Unfortunately Blueprint Assist overrides this to mean "Disconnect" which is confusing once you've got used to UE5's behaviour.

I think this keyboard shortcut should be changed to something else.

**Comment by fpwong** [comment]
Hi, thanks for letting me know. I think I will change the default keyboard shortcut to `ALT+D` in the next update.
