### ISSUE TITLE
Warning about missing image in 5.1

### ISSUE THREAD

**Issue by Ares9323** [fpwong/BlueprintAssistWiki#106]
Hi, I noticed this warning, you might want to have a look at it (I checked the engine folder and the file has been probably removed, I don't know where you are using it but it might break something).

EDIT: I'm assuming the issue is from your plugin  because it's between two LogBlueprintAssist, but in case it's not I'm sorry!

![image](https://user-images.githubusercontent.com/46932745/213939492-589be687-b81f-484d-94bb-10ded4f5540b.png)

Here's the path if you want to copy/paste: `Engine/Content/Editor/Slate/Common/PlainBorder.png`

**Comment by fpwong** [comment]
Hi, thanks for letting me know. It seems they moved this image out of the Editor folder to `Engine/Content/Slate/Common/PlainBorder.png` in 5.1. This will be fixed in the next update.

**Comment by fpwong** [comment]
Fixed in 4.1.0

**Comment by fpwong** [comment]
I noticed this warning message is still being logged. I was using the engine's PlainBorder image previously but now I am loading it myself. 

So I guess they are trying to use the old image path in the engine code too.
