### ISSUE TITLE
Faster formatting option doesn't reformat after a node position changes

### ISSUE THREAD

**Issue by sj-bt** [fpwong/BlueprintAssistWiki#107]
Only with the "Enable Faster Formatting" option set does this problem occur.

1. Create a node
![image](https://user-images.githubusercontent.com/46612978/216736964-586c9bfb-000e-449f-bb27-1e1092554e41.png)

2. Reformat graph using CTRL+R or F with it highlighted
![image](https://user-images.githubusercontent.com/46612978/216737020-f0b36034-c17a-427b-8530-f6a8f2e85b15.png)

3. Move the recently formatted node
![image](https://user-images.githubusercontent.com/46612978/216737067-46671cc7-4176-41a7-a3b5-27d204113b9e.png)

4. Note that pressing CTRL+R or highlighting the node and pressing F does not reformat the nodes.  Refreshing node sizes (CTRL+SHIFT+R) is a workaround when this option is set.

5. Disabling the "Enable Faster Formatting" option doesn't have the same problem.

I stepped through the code, and I would expect line 2621 of EdGraphFormatter.cpp to return true, but when it tries to call "GetFormattedNodes()" the NodePool is Empty so OutNodes is returned Empty as well.

**Comment by fpwong** [comment]
Hi @sj-bt, thanks for looking into this. It has been quite a while since I have revisited this setting. I'll see what I can do to get this working again.

**Comment by fpwong** [comment]
Fixed in 4.1.2. This setting is still experimental though, please let me know if you encounter any issues.
