### ISSUE TITLE
Engine crashing after opening the blueprint search CTRL+SHIFT+F

### ISSUE THREAD

**Issue by rkgdgames** [fpwong/BlueprintAssistWiki#108]
UnrealEditor_SlateCore!TArray<TSharedRef<SWindow,1>,TSizedDefaultAllocator<32> >::RemoveAll<<lambda_b7431a968cb5e605897b83099aef9c29> >() [F:\UnrealEngine5\Engine\Source\Runtime\Core\Public\Containers\Array.h:2418]
UnrealEditor_SlateCore!FSlateWindowHelper::ArrangeWindowToFront() [F:\UnrealEngine5\Engine\Source\Runtime\SlateCore\Private\Application\SlateWindowHelper.cpp:20]
UnrealEditor_SlateCore!SWindow::AddChildWindow() [F:\UnrealEngine5\Engine\Source\Runtime\SlateCore\Private\Widgets\SWindow.cpp:1830]
UnrealEditor_Slate!FSlateApplication::AddWindowAsNativeChild() [F:\UnrealEngine5\Engine\Source\Runtime\Slate\Private\Framework\Application\SlateApplication.cpp:2099]
UnrealEditor_Slate!FSlateNotificationManager::CreateStackForArea() [F:\UnrealEngine5\Engine\Source\Runtime\Slate\Private\Framework\Notifications\NotificationManager.cpp:151]
UnrealEditor_Slate!FSlateNotificationManager::AddNotification() [F:\UnrealEngine5\Engine\Source\Runtime\Slate\Private\Framework\Notifications\NotificationManager.cpp:211]
UnrealEditor_BlueprintAssist!FBAGraphHandler::ShowSizeTimeoutNotification() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistGraphHandler.cpp:1077]
UnrealEditor_BlueprintAssist!TBaseRawMethodDelegateInstance<0,FBAGraphHandler,void __cdecl(void),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [D:\RocketSync\5.0.0-19505902+++UE5+Release-5.0\Working\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:469]
UnrealEditor_BlueprintAssist!FBADelayedDelegate::Tick() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistDelayedDelegate.cpp:19]
UnrealEditor_BlueprintAssist!FBAGraphHandler::UpdateCachedNodeSize() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistGraphHandler.cpp:1908]
UnrealEditor_BlueprintAssist!FBAGraphHandler::Tick() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistGraphHandler.cpp:485]
UnrealEditor_BlueprintAssist!FBATabHandler::Tick() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistTabHandler.cpp:51]
UnrealEditor_BlueprintAssist!FBAInputProcessor::Tick() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistInputProcessor.cpp:95]
UnrealEditor_Slate!FSlateApplication::FinishedInputThisFrame() [F:\UnrealEngine5\Engine\Source\Runtime\Slate\Private\Framework\Application\SlateApplication.cpp:1376]
UnrealEditor!FEngineLoop::Tick() [F:\UnrealEngine5\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:5199]
UnrealEditor!GuardedMain() [F:\UnrealEngine5\Engine\Source\Runtime\Launch\Private\Launch.cpp:183]
UnrealEditor!GuardedMainWrapper() [F:\UnrealEngine5\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:147]
UnrealEditor!LaunchWindowsStartup() [F:\UnrealEngine5\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:283]
UnrealEditor!WinMain() [F:\UnrealEngine5\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:330]
UnrealEditor!__scrt_common_main_seh() [d:\a01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]

**Comment by rkgdgames** [comment]
btw, its happening this when I try to open it with a Widget open. On other class it work fine.

**Comment by fpwong** [comment]
Thanks for reporting this. A few questions:

* Does this crash happen when you press `CTRL+SHIFT+F` on the widget blueprint when it is in Designer mode or Graph mode or both?
* Does the crash happen on a fresh widget blueprint with default nodes or no nodes?
* Do you have the setting `DetectNewNodesAndCacheNodeSizes` enabled?

**Comment by rkgdgames** [comment]
- Sorry delay. It happened while in designer mode. Didnt tried the Graph one.
- It was a fresh widget.
- I do have this option enabled.

**Comment by fpwong** [comment]
Sorry I am still unable to replicate this issue

* Does this happen every time you press `CTRL+SHIFT+F` in designer mode?
* If not does it happen on every FRESH widget blueprint in designer mode?
* Does it still happen if you turn off `DetectNewNodesAndCacheNodeSizes`?

In theory this crash should only occur on fresh widget blueprints. The plugin is trying to calculate node sizes, once it does it successfully, it shouldn't need to do it again (until their size changes).

**Comment by rkgdgames** [comment]
Its hard to say, it just happened with one blueprint in all the time. But, I dont often use this option. So, dont know how to help you much. Its not happening anymore as well

**Comment by fpwong** [comment]
I am not sure how to fix this right now, I will leave this issue up for a while in case someone encounters this. Once again thanks for reporting this crash 👍

**Comment by rkgdgames** [comment]
what I can say for suer is: It was a source engine of unreal 5.0 and it was on  a widget and I was trying to look for stuff XD sorry for leak details. Love your plugin for years.
