### ISSUE TITLE
Shift+Del (delete and link) command override default Unreal behavior and doesn't work on knot nodes

### ISSUE THREAD

**Issue by sdugloudYBG** [fpwong/BlueprintAssistWiki#110]
The Shift+Delete command to "Delete and Keep Links" override the same native command from Unreal (DeleteAndReconnectNodes).
While I like the fact that the BlueprintAssist version reconnect the Sequence and Branch nodes if they are deleted (which the native Unreal version don't), your version doesn't work on non-execution knot nodes, and the link is simply removed without reconnection.
I had to disable that command on our custom engine build for that reason unfortunately :( .

**Comment by fpwong** [comment]
Hi @sdugloudYBG, thanks for letting me know. This has been on my TODO for much too long, where this feature (and swap nodes) were not applying to pure nodes at all. I'll try to add this into the next version.

**Comment by fpwong** [comment]
Fixed in 4.1.2 (I haven't got to fixing the "swap nodes" for pure nodes yet though)
