### ISSUE TITLE
Swap node left/right command often fails to re-order the moved nodes

### ISSUE THREAD

**Issue by sdugloudYBG** [fpwong/BlueprintAssistWiki#111]
I don't have a 100% repro, but it happens very often (~70%) that when using the swap node command (in any direction), the nodes are not properly re-ordered and end up stacked on one another.
See the before and after screens below:
![SwapNodeBug_Before](https://user-images.githubusercontent.com/94921007/218808798-5bf18f9a-3fe7-4363-b8da-f51057b6dd14.png)
![SwapNodeBug_After](https://user-images.githubusercontent.com/94921007/218808799-6af3bd11-c2ed-4e93-8bec-f97aaa2561dd.png)
I think it is important to note that we have disabled the auto-formatting by default on our project (_bGloballyDisableAutoFormatting=true_).

I suspect a conflict with the Group Movement feature, for 2 reasons:
- When this happens, we have to Undo twice to go back to previous state, instead of once only when it works well. And the first transaction undone is "Group Move Nodes" (followed by the "Swap Nodes" - the real transaction I want to undo).
- If I change the _GroupMovementChords_ in the settings to use another key than LeftShift or LeftCtrl, I can't repro the issue, and the swap command work perfectly fine. That is my local fix for now :P .

Hope this will help identify and fix the bug :) .
Thanks in advance !

**Comment by fpwong** [comment]
Hi @sdugloudYBG, I do believe this was fixed in a recent update (4.1.0). If you are already on this version or 4.1.1 let me know and I'll have another look at this.

**Comment by sdugloudYBG** [comment]
Indeed, just tried it on 4.1.1 and I can't seem to repro the issue.
Thanks a lot @fpwong !
