### ISSUE TITLE
Feedback: would be great to have a setting to disable certain commands

### ISSUE THREAD

**Issue by sdugloudYBG** [fpwong/BlueprintAssistWiki#112]
On our project, we wanted the BlueprintAssist plugin mostly for the node related commands that are super neat (Replace Node, Swap Node, Link Nodes Between Wires, Disconnect Node Execution, Format Node Selectively, Shift Drap Nodes, Connect Unlinked Pins, Group Nodes) - thanks for that :D .
But the navigation though pins in a node and the edition of specific selected pin is not something we were looking for. Especially since the SelectPin command override the native Unreal command to move nodes around (though the arrows). So I disabled those commands manually in our custom version, but I wanted to report it :) .
Maybe this could be an editor setting, to disable the pin-only navigation and edition commands ? Or even, have the possibility to cherry-pick the commands we want to enable or disable though the plugin (for the whole set of ~40 commands) ?

**Comment by fpwong** [comment]
Hmm it would be extremely useful to disable any command without needing to remove the hotkey. Best for this to be able to disable any command across the entire editor but I don't see a way of doing that right now. 

I'll see how hard it is to add a checkbox to the BA hotkey menu to support this.

**Comment by fpwong** [comment]
This has been added in 4.1.5. You can find a checkbox in the Hotkey Menu (`CTRL+SHIFT+F1`) which will disable the command when unchecked. This will change the setting `Blueprint Assist Advanced > Disabled Commands`.
