### ISSUE TITLE
Dangling nodes

### ISSUE THREAD

**Issue by ChuckSavage** [fpwong/BlueprintAssistWiki#113]
Sometimes nodes just dangle. I'd bring this up in a discord if you had one to ask why.

![image](https://user-images.githubusercontent.com/844259/219767124-3b9bf906-c3ec-45a6-81be-36f17bc8b79f.png)

**Comment by fpwong** [comment]
Can you try running `Refresh Node Size (CTRL + SHIFT + R)` on these two nodes?
