### ISSUE TITLE
Bug : almost every click in the BP mark it as unsaved

### ISSUE THREAD

**Issue by tshabi8** [fpwong/BlueprintAssistWiki#115]
UE 5.0.3
Plugin: 4.1.3

I have this issue where almost any click in BP mark it as "unsaved" (asterisk) as I did change something (but I didn't).
Since I'm using a source control this is also checking out the file which is very annoying.

Thanks!

**Comment by fpwong** [comment]
Hi @tshabi8, sorry about this. I am able to replicate this issue and will submit a fix for this as soon as possible.

**Comment by fpwong** [comment]
This has been fixed in 4.1.4
