### ISSUE TITLE
Does Alt+D /Ctrl +shif + D work properly?

### ISSUE THREAD

**Issue by pasunna** [fpwong/BlueprintAssistWiki#116]
mine doesn't work at all 5.1.1

**Comment by fpwong** [comment]
Yes they both should work in the latest version. But I have changed the default mapping for disconnect all links from `Ctrl+Shift+D` to `Alt+Shift+D`.
* `Alt+D` will disconnect execution pins (or the first in / out for pure nodes)
* `Alt+Shift+D` will disconnect all pins on the node
