### ISSUE TITLE
Improved camera movement in graphs

### ISSUE THREAD

**Issue by alexander-clarke** [fpwong/BlueprintAssistWiki#119]
The way that camera/view/look movement is done in graphs currently does not handle multiple inputs very well. 

What I mean by this is if I hit shift-right and then press shift-up I expect to me to move 45 degrees up right, instant I move straight up.

 Additionally if I press shift-right twice I expect to move twice the distance. I only move twice the distance if I wait for the camera to stop before I input the key again. It would be better if no matter how long it takes me for to enter the key again it is consistent. 
 
 Less important to my workflow, but also holding the key could also make the camera keep moving

**Comment by fpwong** [comment]
Thanks for letting me know about this. Idk what I was thinking when I coded this, should have made it additive from the start. This will be included in the next update.

Holding the key is a bit more involved and I'm not sure if I want to go down this direction. But perhaps in the future I'll have a look. If anyone else is really interested in this feature reply here and I'll make it a priority.

**Comment by fpwong** [comment]
Fixed in 4.1.6
