### ISSUE TITLE
Crash (UE 4.22, v2.0.0)

### ISSUE THREAD

**Issue by r4qtor** [fpwong/BlueprintAssistWiki#12]
Formatting many nodes using F or all using CTRL+R crashes Editor.

> 
> Assertion failed: OwningNode [File:D:\RocketSync\4.22.0-5660361+++UE4+Release-4.22\Working\Engine\Source\Runtime\Engine\Classes\EdGraph/EdGraphPin.h] [Line: 474]
> 
> UE4Editor_Core!FWindowsErrorOutputDevice::Serialize() [d:\build\++ue4\sync\engine\source\runtime\core\private\windows\windowserroroutputdevice.cpp:79]
> UE4Editor_Core!FOutputDevice::LogfImpl() [d:\build\++ue4\sync\engine\source\runtime\core\private\misc\outputdevice.cpp:71]
> UE4Editor_Core!FDebug::AssertFailed() [d:\build\++ue4\sync\engine\source\runtime\core\private\misc\assertionmacros.cpp:440]
> UE4Editor_Core!FDebug::CheckVerifyFailedImpl() [d:\build\++ue4\sync\engine\source\runtime\core\private\misc\assertionmacros.cpp:418]
> UE4Editor_BlueprintAssist!FBAUtils::CreateKnotNode() [d:\build\++portal+dev-marketplace+full\sync\localbuilds\plugintemp\hostproject\plugins\blueprintassist\source\blueprintassist\private\blueprintassistutils.cpp:334]
> UE4Editor_BlueprintAssist!FKnotNodeCreation::CreateKnotNode() [d:\build\++portal+dev-marketplace+full\sync\localbuilds\plugintemp\hostproject\plugins\blueprintassist\source\blueprintassist\graphformatters\graphformattertypes.cpp:165]
> UE4Editor_BlueprintAssist!FEdGraphFormatter::CreateKnotTracks() [d:\build\++portal+dev-marketplace+full\sync\localbuilds\plugintemp\hostproject\plugins\blueprintassist\source\blueprintassist\graphformatters\edgraphformatter.cpp:1266]
> UE4Editor_BlueprintAssist!FEdGraphFormatter::FormatNode() [d:\build\++portal+dev-marketplace+full\sync\localbuilds\plugintemp\hostproject\plugins\blueprintassist\source\blueprintassist\graphformatters\edgraphformatter.cpp:212]
> UE4Editor_BlueprintAssist!FBAGraphHandler::FormatNodes() [d:\build\++portal+dev-marketplace+full\sync\localbuilds\plugintemp\hostproject\plugins\blueprintassist\source\blueprintassist\private\blueprintassistgraphhandler.cpp:1477]
> UE4Editor_BlueprintAssist!FBAGraphHandler::UpdateNodesRequiringFormatting() [d:\build\++portal+dev-marketplace+full\sync\localbuilds\plugintemp\hostproject\plugins\blueprintassist\source\blueprintassist\private\blueprintassistgraphhandler.cpp:1126]
> UE4Editor_BlueprintAssist!FBAGraphHandler::Tick() [d:\build\++portal+dev-marketplace+full\sync\localbuilds\plugintemp\hostproject\plugins\blueprintassist\source\blueprintassist\private\blueprintassistgraphhandler.cpp:288]
> UE4Editor_BlueprintAssist!FBATabHandler::Tick() [d:\build\++portal+dev-marketplace+full\sync\localbuilds\plugintemp\hostproject\plugins\blueprintassist\source\blueprintassist\private\blueprintassisttabhandler.cpp:44]
> UE4Editor_BlueprintAssist!FBAInputProcessor::Tick() [d:\build\++portal+dev-marketplace+full\sync\localbuilds\plugintemp\hostproject\plugins\blueprintassist\source\blueprintassist\private\blueprintassistinputprocessor.cpp:311]
> UE4Editor_Slate!FSlateApplication::InputPreProcessorsHelper::Tick() [d:\build\++ue4\sync\engine\source\runtime\slate\private\framework\application\slateapplication.cpp:7520]
> UE4Editor_Slate!FSlateApplication::FinishedInputThisFrame() [d:\build\++ue4\sync\engine\source\runtime\slate\private\framework\application\slateapplication.cpp:1604]
> UE4Editor!FEngineLoop::Tick() [d:\build\++ue4\sync\engine\source\runtime\launch\private\launchengineloop.cpp:3945]
> UE4Editor!GuardedMain() [d:\build\++ue4\sync\engine\source\runtime\launch\private\launch.cpp:168]
> UE4Editor!GuardedMainWrapper() [d:\build\++ue4\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:145]
> UE4Editor!WinMain() [d:\build\++ue4\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:275]
> UE4Editor!__scrt_common_main_seh() [d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
> kernel32
> ntdll

**Comment by fpwong** [comment]
Hi r4qtor, does this crash always occur on one of your functions when you press F? If so, could you post a screenshot of that function?

**Comment by r4qtor** [comment]
Sorry for late reply. It was a huge Blueprint I was trying to format, but I pinned it down to the following Event:

![huihuihuihui](https://user-images.githubusercontent.com/275251/66307809-b1e20a00-e905-11e9-9878-978346ea896c.PNG)

Pressing F on the Event reliably crashes the editor.

**Comment by fpwong** [comment]
Thanks, can confirm that this crashes on my end. Should be fixed in the next update.

**Comment by fpwong** [comment]
Update for version 2.0.2 was released, can you confirm that it fixed the crash?
