### ISSUE TITLE
Auto-generating parent node doesn't hook up additional pins correctly

### ISSUE THREAD

**Issue by geordiemhall** [fpwong/BlueprintAssistWiki#122]
Noticed this when adding the `Event Async Physics Tick` node, but seems like it also happens to other events with multiple pins like `OnMovementModeChanged`.

The parent node that gets automatically inserted seems to get auto-wired incorrectly (maybe an off-by-one?):

![image](https://user-images.githubusercontent.com/3511383/231916010-a5769fa4-d869-4824-9738-5bdf58383cae.png)

**Comment by fpwong** [comment]
Hi @geordiemhall, thanks for letting me know. This will be fixed in the next update.

**Comment by fpwong** [comment]
Fixed in 4.1.7
