### ISSUE TITLE
FormatAllEvents ignores AlignExecNodesTo8x8Grid 

### ISSUE THREAD

**Issue by wickerman123** [fpwong/BlueprintAssistWiki#124]
Loving this plugin! However I've noticed that when using the Formal All action, root nodes are not aligned to the 8x8 Grid - only when using Format Selected does this happen. It would be great if the Align to 8x8 Grid rule was enforced when using Format All.

Format All Result:
![image](https://github.com/fpwong/BlueprintAssistWiki/assets/5807444/427bc537-7630-44f7-86f4-c7a8daf094ca)

Format Selected Result:
![image](https://github.com/fpwong/BlueprintAssistWiki/assets/5807444/ed39026a-2539-415b-94b5-71793b826323)

**Comment by fpwong** [comment]
Thanks for letting me know, I'll try to fix this in the next update.

**Comment by fpwong** [comment]
I attempted to fix this in 4.2.0 but I did not test any edge cases. Please comment here if you find any problems and I'll reopen this issue.
