### ISSUE TITLE
Feature Request: Support Validated Get Nodes

### ISSUE THREAD

**Issue by sbseltzer** [fpwong/BlueprintAssistWiki#129]
You can right click on Variable Get nodes and convert them to Validated Variable Get nodes, which combines the functionality of the IsValid macro. Would be nice to have a shortcut that toggles between the normal and validated node types. Additionally, you can use Ctrl+Drag on a property to place a normal Get node, so having an additional key combo that instead places the validated version would also be nice (Ctrl+Alt+Drag?)
![image](https://github.com/fpwong/BlueprintAssistWiki/assets/317916/0f95a53e-d5d6-4be0-bb84-0bc98b88b904)

**Comment by fpwong** [comment]
Hi @sbseltzer, I'll add a keyboard shortcut for this in the next update. As for the drag placement: the code for this is not very extendable. I think this addition would be better suited as an engine pull request.

**Comment by sbseltzer** [comment]
Do you think we could have this toggle purity of cast nodes as well?

**Comment by fpwong** [comment]
> Do you think we could have this toggle purity of cast nodes as well?

Already added it 😉

**Comment by fpwong** [comment]
Added in 4.2.0
