### ISSUE TITLE
Selective Formatting and Pin Selection Not Working in Material Graphs

### ISSUE THREAD

**Issue by alexander-clarke** [fpwong/BlueprintAssistWiki#132]
In a material graph, if I try to selectively format the currently selected nodes, all nodes are formatted
Similarly, if I set the new node format style to only format new nodes, all nodes are formatted

Also, pin selection seems to not work when using the cursor? I can't click on a pin to have it be my currently selected pin, I also can't use the pin connect hotkey to connect the currently selected pin to the hovered pin

Relatedly but less priority, the material format is not great, leaving a lot more space around nodes than is really required

**Comment by fpwong** [comment]
> In a material graph, if I try to selectively format the currently selected nodes, all nodes are formatted

Thanks for letting me know, I'll try to fix this in the next update

> Pin selection seems to not work when using the cursor?

There was a really bad bug with the material graph (and possibly every graph) where the cursor state would get stuck on a pin. This would cause all your keyboard commands to stop working until you fixed it by manually unclicking the pin. I ran into it a couple times and it was bad enough to disable this altogether. That being said, this was quite a long time ago so perhaps it has been fixed. I will add a setting next update to re-enable this.

> Relatedly but less priority, the material format is not great, leaving a lot more space around nodes than is really required

You can change this by going to Editor Preferences and searching for `non blueprint formatter settings`. Then look for `MaterialGraph > Padding`. I agree that these values need updating, will tweak these in the next update.

---

I cannot really recommend using the formatter for the material editor at the current state. This formatter is actually being used for all non-blueprint graphs so it was designed to be mostly top down layout. I may look into making some options to allow for a tree / centered layout.

If you use heavy use of named reroutes it may be not too bad, but for material graphs which are all connected to the root node the graph is not very readable.

**Comment by fpwong** [comment]
Fixed in 4.2.0
