### ISSUE TITLE
Autoformatting changes logic of the script

### ISSUE THREAD

**Issue by qwe321** [fpwong/BlueprintAssistWiki#136]
Gate flow input gets disconnected after autoformatting. Here is example setup: 
![image (2)](https://github.com/fpwong/BlueprintAssistWiki/assets/7630552/e826a306-da9d-4a04-8459-126fa6422819)

Here is how it looks after auto formatting:
![image (3)](https://github.com/fpwong/BlueprintAssistWiki/assets/7630552/ae4877e2-d76b-484e-baac-df00d9d1c0b3)

Note the "Sequence" and "For each" node, as it plays some role here. "For each" can be replaced with some other nodes to reproduce similar bug, i.e. Play Haptic Effect node. Autoformatting becomes totally unreliable as it significantly changes the logic of the script.
Unreal Engine version stock 5.1.1, BlueprintAssist 4.2.0 from the Marketplace

**Comment by fpwong** [comment]
Hi @qwe321, sorry about this. I am able to replicate this bug and will have this fixed asap.

**Comment by fpwong** [comment]
This has been fixed in 4.2.1
