### ISSUE TITLE
Could you please fix this bug?

### ISSUE THREAD

**Issue by chrislvl** [fpwong/BlueprintAssistWiki#137]
<img width="316" alt="image" src="https://github.com/fpwong/BlueprintAssistWiki/assets/40774484/ede3b4b5-178a-4fd8-9698-79729fb48923">

**Comment by fpwong** [comment]
Hi @chrislvl, this has been fixed in 4.2.1. You should have an update in the marketplace 👍

**Comment by chrislvl** [comment]
Awesome, thanks!
