### ISSUE TITLE
”FBAUtils::GetBlueprintEditorForGraph“ function has some problem

### ISSUE THREAD

**Issue by MossisPaul** [fpwong/BlueprintAssistWiki#142]
Hi,I found a question in "FBAUtils::GetBlueprintEditorForGraph" Function,because I can not use "convert get to set "and "generated getter and setter"，now I fix the problem with a simple function,maybe you have a great Solution
old code:
{
        if (UBlueprint* Blueprint = Cast<UBlueprint>(Graph->GetOuter()))
        {
          ......
        }
}
new code:
{
        UBlueprint* Blueprint = nullptr;
	UObject* temp = Graph->GetOuter();
	//
	while (Blueprint == nullptr)
	{
		Blueprint = Cast<UBlueprint>(temp);
		temp = temp->GetOuter();
	}
        if (Blueprint)
        {
          ......
        }
}

**Comment by fpwong** [comment]
Hi @MossisPaul, thanks for letting me know about this bug and the solution.

I will add this in the next update 👍

**Comment by fpwong** [comment]
Added in 4.2.4
