### ISSUE TITLE
[Bug] Expansion nodes cannot recalculate occupancy

### ISSUE THREAD

**Issue by millionart** [fpwong/BlueprintAssistWiki#144]
![image](https://github.com/fpwong/BlueprintAssistWiki/assets/7535532/0a4b2beb-2fba-4730-b828-58e7b3deb20f)

**Comment by fpwong** [comment]
This should be fixed in 4.2.5. However you may need to select this blend node and run `Refresh Node Size (CTRL+SHIFT+R)` once to calculate the correct size but after that it should automatically update.
