### ISSUE TITLE
[Bug] Some formatting in macros doesn't work

### ISSUE THREAD

**Issue by millionart** [fpwong/BlueprintAssistWiki#145]
Now
![image](https://github.com/fpwong/BlueprintAssistWiki/assets/7535532/a309e852-87c8-4fe9-ac4e-aa8efffaaeff)
Better
![image](https://github.com/fpwong/BlueprintAssistWiki/assets/7535532/2479c991-6777-4308-9d9b-f20afd6f36f3)

**Comment by fpwong** [comment]
Thanks for letting me know, this will be fixed in the next update.

**Comment by fpwong** [comment]
Fixed in 4.2.4
