### ISSUE TITLE
[Bug] formatting breaks the AutoSizeComments position

### ISSUE THREAD

**Issue by millionart** [fpwong/BlueprintAssistWiki#146]
It seems that auto-formatting breaks the AutoSizeComments position in ALS_AnimBP>LayerBlending
I don't know how to describe the problem, it's very complicated and I always have trouble formatting into the expected form in this layer, the AutoSizeComments always fly off into the distance every time!
![image](https://github.com/fpwong/BlueprintAssistWiki/assets/7535532/26c4ebf0-2790-464d-8b21-ad3bcb42c09f)
![image](https://github.com/fpwong/BlueprintAssistWiki/assets/7535532/945f8a32-1cd7-44ae-92ac-bf6a5b80846d)
![image](https://github.com/fpwong/BlueprintAssistWiki/assets/7535532/616edd22-d21e-4c30-aec3-cbcc8068f77d)
![image](https://github.com/fpwong/BlueprintAssistWiki/assets/7535532/59aea254-04ca-4f7c-be05-fe7d76c6a006)
![image](https://github.com/fpwong/BlueprintAssistWiki/assets/7535532/417d46ab-abd9-4086-bbbb-733956859207)

**Comment by fpwong** [comment]
Hi, this was quite a serious bug so I submitted an update yesterday for this (v4.2.4). Should be out on the marketplace now along with the fix for #145.

**Comment by millionart** [comment]
![image](https://github.com/fpwong/BlueprintAssistWiki/assets/7535532/89af5558-0e39-4a89-8f83-af46f12c025d)
![image](https://github.com/fpwong/BlueprintAssistWiki/assets/7535532/31fb3c69-14c0-4d96-8e8f-6e5879ed753a)
![image](https://github.com/fpwong/BlueprintAssistWiki/assets/7535532/caae1c73-facd-4900-821d-ca4f2dcccb96)

**Comment by fpwong** [comment]
Hi, it is a bit unclear what is going on here. I have opened the same graph in the ALS project (but it is missing some nodes compared to your image) and do not immediately see any issue when formatting.

I am guessing you are formatting the Post Layering node, the entire node tree moves down slightly each time?
Also the "IMPORTANT!!!" comment moves down each time you format?

Is the "IMPORTANT!!!" comment, inside the "Layer Blending" comment?

**Comment by millionart** [comment]
You need to select the node I highlighted in image 1 and format it, and as you guessed, the "IMPORTANT" comment will move down each time!
This is a standalone comment that doesn't contain any content.

**Comment by fpwong** [comment]
> You need to select the node I highlighted in image 1 and format it, and as you guessed, the "IMPORTANT" comment will move down each time! This is a standalone comment that doesn't contain any content.

Thanks again @millionart I was able to reproduce this bug. Should be fixed in 4.2.5.
