### ISSUE TITLE
Unreal doesn't allow download from marketplace anymore without the right engine version

### ISSUE THREAD

**Issue by rickomax** [fpwong/BlueprintAssistWiki#15]
I can't convert the plugin to Unreal 4.18.3, since I can't download the plugin from marketplace using the wrong version. Could you provide a backwards compatible plugin or the plugin release files so I can convert them here?

**Comment by fpwong** [comment]
Hi rickomax, sorry for the late reply. The earliest supported version of the plugin was for 4.20. I have not released a version for 4.18 which is why you can't download it.

**Comment by fpwong** [comment]
Realised I have already discussed this in email with you, will close this issue. I'll send you an update if I ever get to making the plugin backwards compatible.
