### ISSUE TITLE
İssue while connecting nodes in structure to add array with Ctrl+Q shortcut.

### ISSUE THREAD

**Issue by emireskk** [fpwong/BlueprintAssistWiki#150]
https://github.com/fpwong/BlueprintAssistWiki/assets/73273336/d66bb091-88d0-4b5b-8c46-5575559514e9

**Comment by fpwong** [comment]
Hi @emireskk, `CTRL+Q` is the command for [Link Node Between Wires](https://blueprintassist.github.io/features/command-list/#link-nodes-between-wires). I should change the logic so it does nothing in this case as this is not intended behaviour.

Try using `CTRL+SHIFT+Q` which is the command for [Link to Hovered Pin](https://blueprintassist.github.io/features/command-list/#link-to-hovered-pin).

Let me know if this fixes the problem!

**Comment by emireskk** [comment]
@fpwong

Oh, my fault.

It works fine now!
