### ISSUE TITLE
Shift nodes left/right doesn't allow undo of connected nodes

### ISSUE THREAD

**Issue by geordiemhall** [fpwong/BlueprintAssistWiki#151]
Not sure if this is 100% consistent, but I often try to use 'shift nodes left' via `Ctrl + Shift + LeftArrow`, find that it doesn't quite bring everything across properly and want to undo it.

The undo seems to only affect the impure nodes though, and the pure/connected nodes just stay wherever they ended up after the shift, and you have to them manually drag everything back to how it was.

Let me know if it's hard to repro and I can record a gif or something

Thanks!

**Comment by fpwong** [comment]
Yep, just tested and the connected pure nodes do not get reset correctly 👍 

> find that it doesn't quite bring everything across properly and want to undo it.

To clarify, is this also a bug or just when you want to undo? If it is a bug, I think a gif will be helpful for this case.

**Comment by geordiemhall** [comment]
Yeah I was mainly wanting to report the undo not fully undo-ing, the "shift nodes doesn't always arrange things perfectly" seems like a much harder problem to solve rather than just being a simple bug haha.

Here's a gif showing the lack of undo just to be super clear (though this does also show how even with perfectly isolated node inputs, the shifting still mucks with the vertical positioning of the nodes - though I hadn't auto-formatted that graph so maybe it would end up more consistent if I was).


https://github.com/fpwong/BlueprintAssistWiki/assets/3511383/77f66034-f8b5-424e-aab0-f64e314e5a32

**Comment by fpwong** [comment]
Thanks for the video. I think the reason why I made it swap locations directly is because I wanted to make sure that if you swap left then swap right it would stay in the same location. But this has the side effect of ruining the straightened wires (with auto formatting off).

There's probably a better way to do this relative to the pin height so it maintains the straightened wires. I'll see if I can fix this.

**Comment by fpwong** [comment]
This should be fixed in 4.2.7
