### ISSUE TITLE
[Feature Request] Placement offset setting for Knots

### ISSUE THREAD

**Issue by aburak621** [fpwong/BlueprintAssistWiki#152]
Hello! I use Electronic Nodes plugin along with the Blueprint Assist. The format feature puts the reroute nodes, or knots, too close to the edges and this causes undesirable cable placement. Would adding an offset setting be possible for placing knots that would push knots away from the "corner", or the nodes they are connected to, after all the calculations are done?

Current Behaviour:
![lBCvO3oRh0](https://github.com/fpwong/BlueprintAssistWiki/assets/45210031/fa9ca98f-8fc2-4674-a2de-d521181f0608)

Desired Behaviour:
For the X amount of offset, the knots are pushed by X pixels away from their respective corners, or the nodes they are closer to.
![G39ghfI01j](https://github.com/fpwong/BlueprintAssistWiki/assets/45210031/5ff1fe64-ce73-490d-b07f-0c29bfd63023)
Offset at 3X for better understanding:
![5wk0HeB6GR](https://github.com/fpwong/BlueprintAssistWiki/assets/45210031/fd8b0ce1-5512-4fcc-9934-96aadba635ea)

Even when using the normal blueprint wire style, this offset could be useful for personal personal knot placement preferences.

Adding an offset to the following example might not be logical because there is only a single knot on the wires so maybe the offset could be added when there are 2 or more matching knots in a wire.
![UnrealEditor_7FCL4lOhJA](https://github.com/fpwong/BlueprintAssistWiki/assets/45210031/b69593aa-9b14-4572-a7ab-30fa809139b3)

Would this be feasible or even logical according to you? I haven't though off all the cases this would create a problem. Please say so if my request isn't possible or logical.

Thank you for the amazing work.

**Comment by fpwong** [comment]
Hi @aburak621, should be easy enough to add a setting for this. I'll try to get this into the next update 👍

**Comment by aburak621** [comment]
Awesome! Thank you very much!

**Comment by chaixshot** [comment]
![image](https://github.com/fpwong/BlueprintAssistWiki/assets/13221018/933f4208-03b0-4fcc-9724-1eece7383066)
Finally with [Electronic Nodes](https://www.unrealengine.com/marketplace/en-US/product/electronic-nodes?sessionInvalidated=true) and [Flat Nodes](https://www.unrealengine.com/marketplace/en-US/product/flat-nodes).
And look at the bind event can be like this?
![image](https://github.com/fpwong/BlueprintAssistWiki/assets/13221018/b8fe0d74-98c8-4f32-933c-2b00e4402f0d)

**Comment by fpwong** [comment]
@chaixshot This looks like a separate issue. If you disable flat nodes plugin I think this will not happen, can you check this?

The node size will change after enabling / disabling flat nodes plugin. So you need to run the Refresh Node Size command by selecting the nodes and pressing `CTRL + SHIFT + R`.

But I think I know what is causing this, I'll try to fix this in the next update too.

**Comment by chaixshot** [comment]
@fpwong It same size.
![image](https://github.com/fpwong/BlueprintAssistWiki/assets/13221018/a6927036-482c-46e7-be3b-af3e83d98d20)
![image](https://github.com/fpwong/BlueprintAssistWiki/assets/13221018/3c44a91e-59ae-481a-bc9f-002cd731efa1)

**Comment by fpwong** [comment]
@aburak621 Added in 4.2.7. See settings See settings `BlueprintExecutionKnotSettings` and `BlueprintParameterKnotSettings`.

@chaixshot I believe this formatting issue should also be fixed in the latest update. Let me know if it is not.

**Comment by aburak621** [comment]
Thank you very much for your work!

**Comment by aburak621** [comment]
Tested the BlueprintParameterKnotSettings > KnotXOffset with a value of 24 and it works exactly as I expected. Thanks for the update!
