### ISSUE TITLE
[Bug] AutoSizeComments makes 'Show Bubble When Zommed' not work.

### ISSUE THREAD

**Issue by millionart** [fpwong/BlueprintAssistWiki#153]
'Show Bubble When Zommed' does not work when AutoSizeComments is enabled.

**Comment by fpwong** [comment]
Hi @millionart. Please see https://github.com/AutoSizeComments/AutoSizeComments/issues/36

I have just pushed a commit to fix this in the ASC plugin. Should be on the marketplace in a few days.
