### ISSUE TITLE
Exec and node overlaps in somewhat complex blueprint

### ISSUE THREAD

**Issue by ChuckSavage** [fpwong/BlueprintAssistWiki#154]
![image](https://github.com/fpwong/BlueprintAssistWiki/assets/844259/e8f0c3af-e0a2-4e08-a7c0-9b82227adb69)

**Comment by fpwong** [comment]
Hi @ChuckSavage, update should be live on the marketplace now. Let me know if this has been fixed in the latest plugin version (4.2.7)

**Comment by ChuckSavage** [comment]
Thanks - I'd modified that one so couldn't check it, but here's another similarly complex and it looks great. Though hidden in it is another issue, which I'll post separately (can see one node on top row overlaps a struct break).

![image](https://github.com/fpwong/BlueprintAssistWiki/assets/844259/1e220bac-eef3-4d0e-9f34-8f93093a98ed)
