### ISSUE TITLE
Node overlapping struct break

### ISSUE THREAD

**Issue by ChuckSavage** [fpwong/BlueprintAssistWiki#156]
I keep seeing this issue of a struct break being placed 'below' another node, but not far enough below.
![image](https://github.com/fpwong/BlueprintAssistWiki/assets/844259/9434644a-3b6c-421d-bc41-2faea3f1354d)

**Comment by fpwong** [comment]
This is likely because the cached node size is incorrect. You need to manually refresh it by selecting the nodes and hitting Refresh Node Size `CTRL + SHIFT + R`. Let me know if this fixed the issue.

**Comment by ChuckSavage** [comment]
I upgraded to 5.3 and it no longer seems an issue. I can simply click the node and press F

![image](https://github.com/fpwong/BlueprintAssistWiki/assets/844259/4ee2f042-0204-488e-a640-b5b784fe1d7e)
