### ISSUE TITLE
Auto connect no longer works for 2nd+ nodes from an event/function start node

### ISSUE THREAD

**Issue by ChuckSavage** [fpwong/BlueprintAssistWiki#157]
If I create a custom event with a couple variables, as follows and then add a variable to the integer, and then drag off of the bool and type b (for branch) and click it, it no longer gets attached to the exec (before the set of the integer)
![image](https://github.com/fpwong/BlueprintAssistWiki/assets/844259/24d20937-83cc-4b94-a1f4-cdfa1112154d)

**Comment by fpwong** [comment]
A lot of users didn't like this behaviour, so I have changed the behaviour for this to be a keyboard shortcut.
You need to hold `CTRL` when creating a new node to insert between existing wires.

Try opening the node menu and searching for branch then hold `CTRL` when you select the node from the menu.

The hotkey for this can be changed in the Editor Pref -> Blueprint Assist Editor Features -> InsertNewNodeKeyChord

**Comment by fpwong** [comment]
Added a section for this on the wiki

https://blueprintassist.github.io/features/editor-features/#auto-linking-for-new-nodes

**Comment by fpwong** [comment]
After using this for a while, I felt like it was more useful to have it always auto connect. 
So by default now it will always auto connect. And if you hold CTRL it will not auto connect. 
You can invert this behavior in the setting `AlwaysConnectExecutionFromParameter`.
