### ISSUE TITLE
Formatting event connected to "set timer by event" dosen't work well

### ISSUE THREAD

**Issue by tshabi8** [fpwong/BlueprintAssistWiki#16]
![1](https://user-images.githubusercontent.com/28268953/73533987-b25c5e80-4428-11ea-9120-0e83710eaf6e.png)
![2](https://user-images.githubusercontent.com/28268953/73533988-b25c5e80-4428-11ea-9edc-b07b6e71282d.png)

I can't format both events, one cancels the other.

**Comment by fpwong** [comment]
Hi tsbasi8, you can try enabling the setting "treat delegates as execution pins" on. This should fix the issue for this case.

I can confirm this bug does exist without the setting enabled, I will fix this in the next update.
