### ISSUE TITLE
Hotkeys don't work

### ISSUE THREAD

**Issue by rmenapace** [fpwong/BlueprintAssistWiki#161]
Installed the package.  Restarted UE5.3.  Hot keys from the list had no effect.  Tried to reinstall the package.  Got dialog that package was already installed.  Restarted UE5.3.  Hotkeys have no effect.

Can't get any indication that Blue Print assist is installed, other than the package system refusing to reinstall it.

**Comment by fpwong** [comment]
Code plugins are disabled by default. You need to enable them on a per-project basis.

1. Open your Unreal Project
2. In the top toolbar open the plugin window `Edit > Plugins`
3. Search for BlueprintAssist and tick the checkbox to enable it
4. Restart your project

Let me know if you still have any issues

**Comment by rmenapace** [comment]
Got it, thanks!
