### ISSUE TITLE
Overlapping lines

### ISSUE THREAD

**Issue by ChuckSavage** [fpwong/BlueprintAssistWiki#166]
Hey - great plugin

I've got a new issue (I'm using UE 5.3 - latest release). Some lines are overlapping when I format this section of code.

![image](https://github.com/fpwong/BlueprintAssistWiki/assets/844259/05232ad1-81ea-4bdc-804d-08fae3fed0e4)

**Comment by fpwong** [comment]
Hi @ChuckSavage, I made a similar case and it did not have this issue.

![image](https://github.com/fpwong/BlueprintAssistWiki/assets/7879618/77551e0c-a9b9-44a2-b148-1170da2a0db6)

Could you double check your plugin updated correctly? I did fix a similar issue recently in version 4.2.8 (the latest is 4.2.9 but this has only a very small change).

Another thing you can try is selecting all the nodes here and pressing Refresh Node Size `CTRL + SHIFT + R`.

If the issue still persists could you copy the nodes into https://blueprintue.com/ and I'll see if I can replicate this with the exact node setup.

**Comment by ChuckSavage** [comment]
Okay, there was a blueprint assist update available for 5.3 today and just tried it again, it formatted properly. Thanks.

![image](https://github.com/fpwong/BlueprintAssistWiki/assets/844259/622cf60e-08e5-49c2-9b26-48020b400f32)
