### ISSUE TITLE
"Auto Add Parent Node" isn't working

### ISSUE THREAD

**Issue by TobySunspear** [fpwong/BlueprintAssistWiki#167]
With setting enabled
![image](https://github.com/fpwong/BlueprintAssistWiki/assets/112438784/ec510fa5-12a3-49d6-a035-ffef75378a0f)

Creating nodes will not create the parent node
![image](https://github.com/fpwong/BlueprintAssistWiki/assets/112438784/890598cc-f844-4bfb-9c43-37d9e41459e7)

This was working great for a long time and has somewhat recently broken.

Thanks in advance @fpwong , love your work.

Cheers,
Toby

**Comment by fpwong** [comment]
Hi Toby, thanks for letting me know. I've just submitted a fix for this to the marketplace (v4.2.10). Should be out tomorrow.

**Comment by fpwong** [comment]
Fixed in 4.2.10
