### ISSUE TITLE
Can't compile latest version (UE 5.1 Source Code)

### ISSUE THREAD

**Issue by tshabi8** [fpwong/BlueprintAssistWiki#168]
PluginVersion:  4.2.10
UE Version: 5.1.1
OS: Win10

1>   Creating library ..\Plugins\Marketplace\BlueprintAssist\Intermediate\Build\Win64\UnrealEditor\Development\BlueprintAssist\UnrealEditor-BlueprintAssist.suppressed.lib and object ..\Plugins\Marketplace\BlueprintAssist\Intermediate\Build\Win64\UnrealEditor\Development\BlueprintAssist\UnrealEditor-BlueprintAssist.suppressed.exp
1>BlueprintAssistNodeActions.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static void __cdecl FWindowsPlatformApplicationMisc::ClipboardCopy(wchar_t const *)" (__imp_?ClipboardCopy@FWindowsPlatformApplicationMisc@@SAXPEB_W@Z) referenced in function "public: void __cdecl FBANodeActions::CutAndLink(void)" (?CutAndLink@FBANodeActions@@QEAAXXZ)
1>..\Plugins\Marketplace\BlueprintAssist\Binaries\Win64\UnrealEditor-BlueprintAssist.dll : fatal error LNK1120: 1 unresolved externals

**Comment by drojf** [comment]
Looks similar to https://github.com/fpwong/BlueprintAssistWiki/issues/149 "Linker problem when compiling the plugin" ?

The fix there was "Adding `ApplicationCore` to your project's build.cs (in `PublicDependencyModuleNames`)"

fyi @fpwong will be away for about a week so it may be some time before they get back to you with a proper response

**Comment by tshabi8** [comment]
> Looks similar to #149 "Linker problem when compiling the plugin" ?
> 
> The fix there was "Adding `ApplicationCore` to your project's build.cs (in `PublicDependencyModuleNames`)"
> 
> fyi @fpwong will be away for about a week so it may be some time before they get back to you with a proper response

Thank you, I fixed it by adding ApplicationCore  to the **plugin** build.cs (PublicDependencyModuleNames)
@fpwong please update the plugin

**Comment by fpwong** [comment]
Added in 4.2.11
