### ISSUE TITLE
Helix formatting doesn't work sporadically

### ISSUE THREAD

**Issue by impguard** [fpwong/BlueprintAssistWiki#169]
Is there a setting I'm missing for Helix formatting? Here's an example of a simple node that I want to format using Helix formatting that simply doesn't work. It seems to always default to LHS. Other nodes seem fine formatting in the helix style. For context, I've set the default formatting style to Helix project wide.

It's clunky when I format a block and then some stuff is helixed while others are setup in LHS.

![image](https://github.com/fpwong/BlueprintAssistWiki/assets/1912284/66495713-7e03-4d84-bcee-a7fe47c903c8)

**Comment by impguard** [comment]
I have noticed now that helixing seems to only work when it's one parameter? Doesn't helix multiple I believe.

**Comment by impguard** [comment]
Found the documentation buried in the docs :O

```
 If the node has multiple linked parameters, it will switch to left side
 ```
 
 Is there a way...to disable that?

**Comment by fpwong** [comment]
Hi @impguard, yes is intended and currently there is no way to disable this. However it should be easy (hopefully...) to add a setting in the next update to allow for this. Will try to get it into the next update.

**Comment by fpwong** [comment]
Added setting `DisableHelixingWithMultiplePins` in 4.2.12. Forgot to test this one while trying to hotfix another bug, please reopen this if you find any issues.
