### ISSUE TITLE
Crash in Anim BPs (4.24.2)

### ISSUE THREAD

**Issue by darrickyee** [fpwong/BlueprintAssistWiki#17]
This is happening to me with AnimBPs using both the UE skeleton and some custom skeletons.

1. Create a blank C++ project.

2. Add a skeletal mesh to the project and create a new Animation BP for it.

3. Plug something into the Output Pose in the AnimGraph

4. CTRL-R

I reliably get an `Access violation reading location` immediately after doing this (in debug mode).  Any chance this can be fixed?  I love this plugin, but this is a bit of a showstopper for me.

This is with both a Launcher version 4.24.2 project and a project using my own custom source build.  Win64

**Comment by fpwong** [comment]
Thanks darrickyee, can confirm this bug exists and will be fixed in the next update. 

For reference this bug also occurs when formatting parameter nodes, so if you have a chain of only parameter nodes (e.g. append linked to an append) and try to format them it will result in the same crash.

**Comment by darrickyee** [comment]
Thanks. Fyi, it also seems to happen when formatting BP Macro Library nodes.
