### ISSUE TITLE
two very minor bugs

### ISSUE THREAD

**Issue by zlylupaf** [fpwong/BlueprintAssistWiki#176]
"Shift+ backspace" doesn't work with macros, e.g. "while" "sequence"
![image](https://github.com/fpwong/BlueprintAssistWiki/assets/99085114/9544d51e-1a6e-4f80-8805-e15ab0732e99)

the "get a reference to self node" doesn't get formatted when pressing "f"
![image](https://github.com/fpwong/BlueprintAssistWiki/assets/99085114/9f4e8359-0fe5-4733-8798-6308e3ee8940)

very minor issues, so don't worry that much about fixing them etc

**Comment by fpwong** [comment]
Shift+Backspace is the built-in Unreal "delete and keep links" feature (which I didn't know existed 😅). The BA command is Shift+Del which should work for the first case.

There does seem to be some issues with the self node, I'll have a look at this.

**Comment by zlylupaf** [comment]
hm recently found out that Shift+Ctrl+X deletes and keeps links for macros, but Oddly enough Shift+Backspace doesn't
(btw Ctrl+X "cuts" something)

**Comment by fpwong** [comment]
The Shift+Backspace is not my hotkey but the Unreal Editor one. You can find the list of Blueprint Assist hotkeys by pressing `CTRL+SHIFT+F1`.

**Comment by fpwong** [comment]
Fixed in 4.2.15 https://github.com/fpwong/BlueprintAssistWiki/releases/tag/4.2.15
