### ISSUE TITLE
[Feature Request] Shortcut for adding a reroute node 

### ISSUE THREAD

**Issue by dgotbaum** [fpwong/BlueprintAssistWiki#18]
Reroute bodes can really clean up your blueprints, and selecting them from the menus can take time in the long haul. Love your plugin!!

**Comment by fpwong** [comment]
I'll look into adding this in the next update

**Comment by fpwong** [comment]
Was added a while ago. The default hotkey is unbound, so you will need to bind it yourself.

Select a pin and press the hotkey, and it will create a reroute at your cursor.
