### ISSUE TITLE
BPAssist moving newly made nodes breaks Unreal Editor's automatic rename functionality when promoting a variable

### ISSUE THREAD

**Issue by nathanielchapman** [fpwong/BlueprintAssistWiki#180]
After you promote a variable in the editor, the editor then selects the node in the variable lists and puts it into rename mode, so you can quickly rename the variable. However, BPAssist's auto arrange feature steals focus and breaks this nice usability feature from the default editor.

**Comment by fpwong** [comment]
Hi @nathanielchapman, thanks for letting me know. This will be fixed in the next update.

**Comment by fpwong** [comment]
Fixed in 4.2.17
