### ISSUE TITLE
Helixing should allow limiting the number of pins with an explicit count

### ISSUE THREAD

**Issue by Sulfur-CK** [fpwong/BlueprintAssistWiki#182]
In the latest version, the helixing option is either turned off if there is more than one pin or turned on regardless of the number of pins.

However, it would be great if we can specify the number of pins beyond which helixing is disabled e.g. beyond 2 input pins, helixing is disabled.

Thanks!

**Comment by fpwong** [comment]
I believe you are referring to the `Disable Helixing with Multiple Pins` setting?
Should be easy enough to convert this to an integer setting 👍

**Comment by fpwong** [comment]
Added in https://github.com/fpwong/BlueprintAssistWiki/releases/tag/4.2.19. See setting `DisableHelixingPinCount`
