### ISSUE TITLE
Plugin fails to correctly format custom events that are binded to another event

### ISSUE THREAD

**Issue by DeepChallengerVR** [fpwong/BlueprintAssistWiki#183]
Hi, I have noticed that when binding a custom event to another event via "Bind Event to Event X" node, the formatter tends to place nodes in the same space. I have attached a screenshot of the issue, and then I manually formatted the nodes so that you can better see the blueprint nodes.

I am using default settings with formatting style expanded.

![bad](https://github.com/user-attachments/assets/233e3b7c-3423-4721-8955-e08a96f78994)
![better](https://github.com/user-attachments/assets/8997010d-712a-49be-9935-90bb28830336)

**Comment by DeepChallengerVR** [comment]
Playing around with this some more I think the sequence node formatting is also to blame. I'm noticing when you are binding custom events to events and making use of the sequence node, the formatting tends to get unusable. Somewhat of a fix I've found is using your comment boxes plugin and surrounding events with a comment box

**Comment by fpwong** [comment]
Thanks for letting me know I'll look into this

**Comment by fpwong** [comment]
Hi, I have updated the formatting in the new update please let me know if this fixed the issue.

**Comment by DeepChallengerVR** [comment]
Thanks for the update. I'll try next week. I'm on vacation now
