### ISSUE TITLE
Formatting has caused node connections to change. 

### ISSUE THREAD

**Issue by grinwraith** [fpwong/BlueprintAssistWiki#185]
Before:
![image](https://github.com/user-attachments/assets/de6a8488-4901-4598-b5f8-59b9e2012896)
After:
![image](https://github.com/user-attachments/assets/64c00490-1ed5-4896-9992-d1097974d937)

Output Log: 
LogBlueprintAssist: Error: Formatting has caused node connections to change Out: "then (Set IsCustomHit)" > "execute (Apply Point Damage)"
LogBlueprintAssist: Error: Formatting has caused node connections to change In: "execute (Apply Point Damage)" > "then (Set IsCustomHit)"
LogBlueprintAssist: Error: Formatting has caused node connections to change Out: "false (Branch)" > "execute (Line Trace By Channel)"
LogBlueprintAssist: Error: Formatting has caused node connections to change In: "execute (Line Trace By Channel)" > "false (Branch)"

**Comment by fpwong** [comment]
Hi @silentchiron I'm guessing this is after updating to the new version today? I'll look into this.

**Comment by fpwong** [comment]
Alright I have reverted a change I made. You can grab the fix below, it should hopefully be updated in the marketplace by tomorrow.

To build from the source above you can follow the instructions here: https://github.com/AutoSizeComments/AutoSizeComments

**Comment by grinwraith** [comment]
> after updating to the new version today? I'll look into this.

Yes, immediately after updating to today's version.

**Comment by fpwong** [comment]
Thanks for letting me know so fast, you can find the fix in the marketplace now.

**Comment by grinwraith** [comment]
Thank you!  Installed the new build from the marketplace and it works as intended.
