### ISSUE TITLE
Unable to rename variables in scratch modules (niagara)

### ISSUE THREAD

**Issue by eTwistyy** [fpwong/BlueprintAssistWiki#186]
When the plugin is active, we can't rename variables (no matter the varaible type) when editing a scratch module within niagara.

![image](https://github.com/user-attachments/assets/9f568172-9be6-46b3-bd35-af964f72a5bd)

![image](https://github.com/user-attachments/assets/7bcb3f95-df33-4483-82e7-e0d03d4b5642)

**Comment by fpwong** [comment]
Hi @eTwistyy, sorry about that. This will be fixed in the next update. 

As a temporary workaround, you can left click on the graph instead of pressing enter to confirm renaming.

**Comment by eTwisty** [comment]
No problem, thanks for the work around !

**Comment by fpwong** [comment]
This should be fixed in v4.2.21, please let me know if you still have issues.
