### ISSUE TITLE
How to decrease the distance of the nodes?

### ISSUE THREAD

**Issue by LI-100** [fpwong/BlueprintAssistWiki#187]
![image](https://github.com/user-attachments/assets/9f0751b2-6ba7-4ae6-9ed3-f17e7e22633c)

**Comment by fpwong** [comment]
Hi @LI-100, please try disabling the setting `Expand Nodes By Height` which can be found in Editor Pref > Blueprint Assist.

**Comment by LI-100** [comment]
Hi @fpwong  How to decrease these space? Thank you for helping me.

**Comment by LI-100** [comment]
![image](https://github.com/user-attachments/assets/a7b44a0b-b3d5-42d1-ae84-24ae5ddc1650)

**Comment by fpwong** [comment]
Search for `Non Blueprint Formatter Settings` and scroll down until you see `AnimationGraph`. There you can edit the `Padding` setting.

![image](https://github.com/user-attachments/assets/29bd6982-2a7f-4a98-a3fb-54f51d147e7a)
