### ISSUE TITLE
Plugin fails to install with error MD-0011 (UE 5.5.0)

### ISSUE THREAD

**Issue by fhajji** [fpwong/BlueprintAssistWiki#188]
Hello,

Blueprint Assist fails to install for UE 5.5.0 on Windows. The launcher returns code MD-0011.

Apparently, a manifest file is missing:

`[2024.11.13-17.52.36:483][418]LogOnline: Warning: OSS: Invalid response. CorrId=UE4-aaf69b3e4cd857c94ab0f49ea0abc86f-78B635034BC113DAC626AB95F8211450-47C1C26941D2BC4A533986985AD52C89 code=404 errorcode=JsonErrorUnknownCode errormessage=Server error of type JsonErrorUnknownCode errorraw={"Not Found":"Could not find any manifest download info with artifactId=Blueprin5dd30dcb4d35V14"}`

It may or may not be related to the Fab migration, since a few other plugins are affected as well: https://forums.unrealengine.com/t/plugin-installation-error-md-0011-0-after-fab-migration/2083033/65

**Comment by fpwong** [comment]
Hi @fhajji, thanks for letting me know about this. I have raised a support ticket for this, hopefully they will fix it soon.

The 5.5 update is compatible for the older versions of the plugin, as a temporary fix you can follow these steps to build the plugin for 5.5.

https://blueprintassist.github.io/miscellaneous/faq/#building-the-plugin-for-a-custom-unreal-version

**Comment by fpwong** [comment]
This should have been fixed now, please let me know if you still have issues installing.
