### ISSUE TITLE
NodeSizeCache should be in the Saved or Intermediate Directory. 

### ISSUE THREAD

**Issue by donalmacc** [fpwong/BlueprintAssistWiki#191]
The "NodeSizeCache" folder that BPAssist uses shouldn't be in the Plugins/BlueprintAssist/NodeSizeCache folder, it should be in the Intermediate folder (or the saved folder if it's really more than a cache).

**Comment by fpwong** [comment]
That is a good point, I'll change this in the next update!

**Comment by donalmacc** [comment]
Thanks! I've shoved it in `FPaths::ProjectIntermediateDir() / TEXT("BlueprintAssist");`  for now, but happy for it to be `PluginBaseDir / TEXT("Intermediate");` either!

Thanks for the quick reply.

**Comment by fpwong** [comment]
Ahh I knew I had looked into this some time ago. 

* Go to `Editor Pref > Blueprint Assist Advanced` search for  `Cache Save Location`
* Change this from `Plugin` to `Project`

It will change the location to `ProjectFolder/Saved/BlueprintAssist/BlueprintAssistCache.json`

I'll change this as the default option in the next update!

**Comment by fpwong** [comment]
Changed in [4.3.1](https://github.com/fpwong/BlueprintAssistWiki/releases/tag/4.3.1)
