### ISSUE TITLE
Auto Format on BindEvent too narrow

### ISSUE THREAD

**Issue by shufflerror** [fpwong/BlueprintAssistWiki#193]
Hello, thanks for your great timesaver.

After updating today I recognized a annoying behavior on Bind/AssignEvent nodes.
The upcoming nodes are now aligned in one row and overlap each other.

<img width="981" alt="BPAssist_Screenshot" src="https://github.com/user-attachments/assets/e172e7f0-88b7-40c9-8d12-9f3643cbc115" />

Alignment before update:

<img width="813" alt="BPAssist_Screenshot_02" src="https://github.com/user-attachments/assets/87be1d6c-cd99-4017-b595-7dbee1206126" />

Is there any setting to prevent this behavior?

**Comment by fpwong** [comment]
Hi @shufflerror, sorry about this. I have submitted a hotfix for this, should be out soon.

Unfortunately there is no setting to fix this. But as a temporary workaround you can use the `CreateEvent` node and format these events separately.

You can quickly convert to one by right clicking the Event pin on `Bind Event to On GameLoaded` and selecting `Generate Create Event Node`.

![image](https://github.com/user-attachments/assets/881a7311-8ede-44d9-9cd1-cf2ee7dd6180)

**Comment by fpwong** [comment]
Fixed in https://github.com/fpwong/BlueprintAssistWiki/releases/tag/4.3.2

**Comment by shufflerror** [comment]
Wow, it works. Thanks a lot @fpwong .

A little follow up question: 
Is there a method to "freeze" certain node blocks, so they are not effected by ctrl R shortcut?
Sometimes manual alignment would tidy up some long flow chains.

**Comment by fpwong** [comment]
@shufflerror Yes, please see https://blueprintassist.github.io/features/command-list/#toggle-lock-nodes
