### ISSUE TITLE
all shortkeys are hardcoded and there is no way to turn off auto formatting

### ISSUE THREAD

**Issue by ivanesses** [fpwong/BlueprintAssistWiki#2]
please make it possible to change shortkeys and turn off auto formatting in plugin settings

**Comment by fpwong** [comment]
Hi ivanesses, 

The hotkeys for the plugin can be rebound under: Editor Preferences | General | Keyboard Shortcuts | Blueprint Assist Commands

A checkbox setting in the toolbar for "format after you place a node" will be added in the next update.

Please tell me if this solves your issues!

fpwong
