### ISSUE TITLE
[Feature Request] Undo Formatting

### ISSUE THREAD

**Issue by vital-net** [fpwong/BlueprintAssistWiki#20]
Hello,

If I accidentally hit the F key, or if the formatting don't satisfy me, I often cannot use CTRL+Z to go back in time to the original state because Unreal can only undo a limited number of actions.

So I am force to Exit the Blueprint without saving and re-open it, losing all my work in the process.

Could you implement an Undo Formatting Shortcut ? I would be really safer.
Thank you :)

That's my only complain

**Comment by fpwong** [comment]
Hi vital-net, the undo for formatting was bugged and I actually just submitted the update today which will fix this. It should be out in a day or two.

**Comment by fpwong** [comment]
@vital-net The update for v2.2.2 has released, could you confirm that undo is working as you expected?
