### ISSUE TITLE
[Feature Request] Generate Getter and Setter functions with a shortcut

### ISSUE THREAD

**Issue by Unavi** [fpwong/BlueprintAssistWiki#22]
I would like to be able to generate a getter and a setter for a selected variable after I press a shortcut.
After the generation, the functions should be moved into a category named Properties (could be configurable). 

Additionally, variables access type should be set to private after the generation of the getter and setter or should be generally set to private after adding a new one.

**Comment by fpwong** [comment]
Added in latest update (3.0.0)
