### ISSUE TITLE
Undo doesn't undo comment box changes after auto-formatting

### ISSUE THREAD

**Issue by BenVlodgi** [fpwong/BlueprintAssistWiki#23]
To reproduce: 
- have code with a comment box around some code
- press f to format
- the comment box moves
- press undo
=> comment box wont go back to original location/size as it was before the formatting.

**Comment by fpwong** [comment]
Hi Ben, I'll look into this but I would highly suggest you use the AutoSizeComments plugin which should solve this issue.

**Comment by fpwong** [comment]
Update 3.0.0 has released, this issue should be fixed now.
