### ISSUE TITLE
Issue with menus closing after using the editor

### ISSUE THREAD

**Issue by fpwong** [fpwong/BlueprintAssistWiki#24]
> I am getting strange "side effects" from what could be the plugin as it didn't happen before I installed it.
> 
> After a couple minutes of working in the node editor, whenever I press right-mouse-click or tab, the BP menu opens but then disappears right away.
> 
> Then, so as every other menu - can that be related?

Question for user:

- UE4 version?
- Any other BP plugins used?
- Does the issue persist across tabs / Does the issue persist after opening and closing the tab?

**Comment by ghostmize** [comment]
Hello

UE4 the latest - 4.26

Cinema 4D Datasmith is installed but it's not BP related

The issue persists across projects and tabs, and yes also when opening/closing.
It only stops after restarting Unrela

thanks again!

Elad

**Comment by fpwong** [comment]
Hi ghostmize, sadly I never was able to encounter this issue

Update 3.0.0 has released, perhaps a change may have fixed it

Let me know if you are still encountering this issue
