### ISSUE TITLE
Formatting crashes Editor

### ISSUE THREAD

**Issue by OptimisticRaccoon** [fpwong/BlueprintAssistWiki#25]
Using the latest 2.3.6 on 4.26.1, formatting the following Graph:

![4455455](https://user-images.githubusercontent.com/275251/107921811-5602a900-6f6f-11eb-8810-d3485b7becd8.PNG)

crashes the editor:
Assertion failed: OutPin->LinkedTo.Num() == 1 [File:D:/Build/++UE4/Sync/Engine/Source/Editor/GraphEditor/Private/BlueprintConnectionDrawingPolicy.cpp] [Line: 506]

Only happens in AnimBP, using the same node constellation in any other Blueprint works fine.

**Comment by fpwong** [comment]
Formatting this case in the event graph of an animbp works on my side. Could you post your settings? You can do this by going to Editor Preferences > Blueprint Assist and pressing export in the top right.

**Comment by r4qtor** [comment]
Interestingly I'm running default settings, 4.26 has also been a fresh install with no changes. It even crashes in a new project.

**Comment by fpwong** [comment]
Hi OptomisticRaccoon, sadly I have still not encountered this issue.

Update 3.0.0 has been released just now, perhaps a change I made may have fixed this.

Closing it for now, but reopen this if you have this issue again.
