### ISSUE TITLE
Options in "Select variable" menu partially working

### ISSUE THREAD

**Issue by Dvoya** [fpwong/BlueprintAssistWiki#28]
Currently, these options in the Variable selector menu do not work: 
- Components
- Replication
- Rendering
- Actor
- Collision
- LOD
Running on 4.26.1 with no other blueprint modifying plugin.

**Comment by fpwong** [comment]
Thanks, opening the categories is currently broken. Will be fixed in the next update.

**Comment by fpwong** [comment]
Update 3.0.0 has released, this issue should be fixed now.
