### ISSUE TITLE
[Feature Request] Go-to-blueprints after pressing Enter over selection in "Find Results" window

### ISSUE THREAD

**Issue by Dvoya** [fpwong/BlueprintAssistWiki#29]
Basically the same feature as the go-to symbol menu but with the find results window. As of now it requires that you double click the option that you want in the "Find Results" window to "go-to" it.

"Find Results" window is the window that opens up when pressing CTRL+F in blueprint.

**Comment by fpwong** [comment]
If I understand correctly, you mean the default UE4 find results in blueprints from pressing CTRL+F?

Unfortunately I don't have any control over this window. While I could recreate it's functionality it would be too much work for this small feature.
