### ISSUE TITLE
all links are stretching

### ISSUE THREAD

**Issue by ivanesses** [fpwong/BlueprintAssistWiki#3]
all links are stretching out if you create node
https://i.imgur.com/ZLWMf4o.png

**Comment by fpwong** [comment]
Hi ivananess, this is a bit hard to recreate without the rest of the nodes, could you post a screenshot with the entire function?

**Comment by ivanesses** [comment]
It almost always happens if you drag out some intermediate node, which is connected only on one side. Like "get mesh component"
https://i.imgur.com/PP1jKjW.png

**Comment by fpwong** [comment]
Hi ivaness, I was unable to reproduce the issue you were having on the current version of the plugin. Hopefully the issue will be gone in the next update, as I have updated the formatting algorithm quite a lot.

**Comment by ivanesses** [comment]
when it will be available?

**Comment by fpwong** [comment]
Should be end of the week or early next week

**Comment by fpwong** [comment]
Hi ivanesses, the update has been released. Can you check if the issue is still there?
