### ISSUE TITLE
Automaticly created knot nodes connect more than one out nodes.

### ISSUE THREAD

**Issue by yuanb36** [fpwong/BlueprintAssistWiki#32]
![BluePrint Assist bug](https://user-images.githubusercontent.com/11003036/116342475-40ceb400-a815-11eb-9368-27c1016ef968.png)
![BluePrint Assist bug 2](https://user-images.githubusercontent.com/11003036/116342479-42987780-a815-11eb-8391-5e1a845ea0ec.png)

It may cause editor to crash.

**Comment by fpwong** [comment]
Thanks for the report, I recently fixed this issue. The update will be coming soon.

**Comment by fpwong** [comment]
Update 3.0.0 has released, this issue should be fixed now.
