### ISSUE TITLE
UE5 Support

### ISSUE THREAD

**Issue by staniekmarcin** [fpwong/BlueprintAssistWiki#34]
Hi, after today release of Ue5 Early Access I started wondering if there will be UE5 support of this plugin?

**Comment by fpwong** [comment]
Of course :) I'll be adding support in the next update but it'll have to be included in the 4.26 plugin since there's no way to select 5.00 when you submit to the marketplace.

**Comment by staniekmarcin** [comment]
Thank you for quick response ;)

**Comment by fpwong** [comment]
Hi, just wanted to let you know the update is out.

**Comment by staniekmarcin** [comment]
thx!

**Comment by fpwong** [comment]
Should be noted that I just submitted an update which will fix some crashes users had reported as well. Look out for it tomorrow or the day after.
