### ISSUE TITLE
3.1.1 Two Crash Logs

### ISSUE THREAD

**Issue by yuanb36** [fpwong/BlueprintAssistWiki#42]
[BA Crash Log1.txt](https://github.com/fpwong/BlueprintAssistWiki/files/6768665/BA.Crash.Log1.txt)
[BA Crash Log2.txt](https://github.com/fpwong/BlueprintAssistWiki/files/6768666/BA.Crash.Log2.txt)

**Comment by fpwong** [comment]
Hi yuanb36, do you rememeber if there anything in particular which seemed to triggered this crash? 

I believe this crash is related to issue #37 which I suspected had something to do with certain variable types within the blueprint. Did your blueprint contain any complex variable types like custom structs or gameplay tags?

**Comment by fpwong** [comment]
Please download the 3.1.2 update, which should fix this issue.
