### ISSUE TITLE
3.1.1 Crash when drop on return node to create a pin.(random)

### ISSUE THREAD

**Issue by yuanb36** [fpwong/BlueprintAssistWiki#43]
Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0xffffffffffffffff

UE4Editor_Core!rml::internal::freeSmallObject() [d:\dev-enterprise\engine\source\thirdparty\inteltbb\inteltbb-2019u8\src\tbbmalloc\frontend.cpp:2518]
UE4Editor_Core!scalable_free() [d:\dev-enterprise\engine\source\thirdparty\inteltbb\inteltbb-2019u8\src\tbbmalloc\frontend.cpp:2933]
UE4Editor_Core!FMemory::Free() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Core\Public\HAL\FMemory.inl:80]
UE4Editor_Core!FString::~FString()
UE4Editor_BlueprintAssist!TArray<FBPVariableDescription,TSizedDefaultAllocator<32> >::Empty() [D:\Program Files\Epic Games\UE_4.26\Engine\Source\Runtime\Core\Public\Containers\Array.h:1723]
UE4Editor_BlueprintAssist!FBABlueprintHandler::SetLastVariables() [C:\Git Repositories\sas\Plugins\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistBlueprintHandler.cpp:58]
UE4Editor_BlueprintAssist!FBABlueprintHandler::OnBlueprintChanged() [C:\Git Repositories\sas\Plugins\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistBlueprintHandler.cpp:139]
UE4Editor_BlueprintAssist!TBaseRawMethodDelegateInstance<0,FBABlueprintHandler,void __cdecl(UBlueprint *),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [D:\Program Files\Epic Games\UE_4.26\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:469]
UE4Editor_Engine!TMulticastDelegate<void __cdecl(UBlueprint *),FDefaultDelegateUserPolicy>::Broadcast() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Core\Public\Delegates\DelegateSignatureImpl.inl:955]
UE4Editor_BlueprintGraph!UEdGraphSchema_K2::HandleParameterDefaultValueChanged() [D:\Build\++UE4\Sync\Engine\Source\Editor\BlueprintGraph\Private\EdGraphSchema_K2.cpp:7216]
UE4Editor_BlueprintGraph!UEdGraphSchema_K2::DropPinOnNode() [D:\Build\++UE4\Sync\Engine\Source\Editor\BlueprintGraph\Private\EdGraphSchema_K2.cpp:7186]
UE4Editor_GraphEditor!FDragConnection::DroppedOnNode() [D:\Build\++UE4\Sync\Engine\Source\Editor\GraphEditor\Private\DragConnection.cpp:271]
UE4Editor_GraphEditor!SGraphNode::OnDrop() [D:\Build\++UE4\Sync\Engine\Source\Editor\GraphEditor\Private\SGraphNode.cpp:345]
UE4Editor_Slate!<lambda_e356e543718159020736727f05f9aa09>::operator()() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Slate\Private\Framework\Application\SlateApplication.cpp:4870]
UE4Editor_Slate!FEventRouter::Route<FReply,FEventRouter::FBubblePolicy,FPointerEvent,<lambda_e356e543718159020736727f05f9aa09> >() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Slate\Private\Framework\Application\SlateApplication.cpp:378]
UE4Editor_Slate!FSlateApplication::RoutePointerUpEvent() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Slate\Private\Framework\Application\SlateApplication.cpp:4866]
UE4Editor_Slate!FSlateApplication::ProcessMouseButtonUpEvent() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Slate\Private\Framework\Application\SlateApplication.cpp:5356]
UE4Editor_Slate!FSlateApplication::OnMouseUp() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Slate\Private\Framework\Application\SlateApplication.cpp:5321]
UE4Editor_ApplicationCore!FWindowsApplication::ProcessDeferredMessage() [D:\Build\++UE4\Sync\Engine\Source\Runtime\ApplicationCore\Private\Windows\WindowsApplication.cpp:2178]
UE4Editor_ApplicationCore!FWindowsApplication::DeferMessage() [D:\Build\++UE4\Sync\Engine\Source\Runtime\ApplicationCore\Private\Windows\WindowsApplication.cpp:2642]
UE4Editor_ApplicationCore!FWindowsApplication::ProcessMessage() [D:\Build\++UE4\Sync\Engine\Source\Runtime\ApplicationCore\Private\Windows\WindowsApplication.cpp:1046]
UE4Editor_ApplicationCore!FWindowsApplication::AppWndProc() [D:\Build\++UE4\Sync\Engine\Source\Runtime\ApplicationCore\Private\Windows\WindowsApplication.cpp:878]
user32
user32
UE4Editor_ApplicationCore!FWindowsPlatformApplicationMisc::PumpMessages() [D:\Build\++UE4\Sync\Engine\Source\Runtime\ApplicationCore\Private\Windows\WindowsPlatformApplicationMisc.cpp:130]
UE4Editor!FEngineLoop::Tick() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:4748]
UE4Editor!GuardedMain() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Launch\Private\Launch.cpp:169]
UE4Editor!GuardedMainWrapper() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:137]
UE4Editor!WinMain() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:268]
UE4Editor!__scrt_common_main_seh() [d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll
![1](https://user-images.githubusercontent.com/11003036/124705859-e9da0f00-df28-11eb-86c4-f9bc2d303655.png)
![2](https://user-images.githubusercontent.com/11003036/124705879-f1011d00-df28-11eb-9788-5a0d745e4dd7.png)

It does not happen every time. It's a very simple component to play sound effect, only 2 variables and some functions.

**Comment by fpwong** [comment]
Please download the 3.1.2 update which should fix this crash.

**Comment by yuanb36** [comment]
> Please download the 3.1.2 update which should fix this crash.

Where can I download 3.1.2 elsewhere? Currently no notification in official Launcher.

**Comment by fpwong** [comment]
@yuanb36 I do get the latest 3.1.2 version when I download from the marketplace. It should be the latest update for 4.24/4.25/4.26. Perhaps try removing and adding the plugin?
