### ISSUE TITLE
Cannot delete node using delete button if focus is on detail panel or another panel

### ISSUE THREAD

**Issue by Dvoya** [fpwong/BlueprintAssistWiki#46]
If a branch node is created in the event graph when the last click was in the details panel, navigating to that node without the mouse button and hitting "delete" does nothing.

In order to use the delete button to make it working again, you have to click on the event graph node or click on the event graph first and then delete the node. 

It can still be done using the pin actions, but it doesn't work with delete for some reason.

**Comment by fpwong** [comment]
Hi Dvoya, this is actually part of the engine behaviour. When you navigate away from the graph, it loses keyboard focus so it doesn't process keyboard commands such as delete. 

That's why the BA commands work without focus of the graph while delete does not. You can use the BA commande, Shift + Delete to delete nodes using the plugin.

Do let me know if there are other commands which you find the same issue with.

**Comment by Dvoya** [comment]
Great work around! But darn, I was hoping this wasn't the case. I noticed I also wasn't able to set blueprint break points either with the same steps.

**Comment by Dvoya** [comment]
Is there a way to set focus to the event graph without clicking on it? 

Similar to how you focus the search boxes?

**Comment by fpwong** [comment]
> Is there a way to set focus to the event graph without clicking on it?

It is quite easy to add implement this, I'll add it in the next update. However I will probably not give it a hotkey by default, since I don't think it's a feature many users will use.

**Comment by Dvoya** [comment]
That sounds great! Looking forward to it!

**Comment by Dvoya** [comment]
If possible could you also add an option to have the event graph or loaded graph automatically focused when opening the asset? That is the main time at which I am always having to click on the event graph or opened graph.

**Comment by fpwong** [comment]
> If possible could you also add an option to have the event graph or loaded graph automatically focused when opening the asset? That is the main time at which I am always having to click on the event graph or opened graph.

That's a great idea, will add that too.
