### ISSUE TITLE
[QOL Feature Request] Option to zoom to selection automatically after creating linked node

### ISSUE THREAD

**Issue by Dvoya** [fpwong/BlueprintAssistWiki#48]
Hi, I'd like to request a feature: Automatically use the "zoom to selection" feature in the blueprint editor upon creation of after creating a linked execution node. Similar to your feature where after a node will automatically be formatted after creation, I'm wanting it to zoom to that selection right afterwards.

All too often after creating a new node (let's say branch) I have to then pan my screen over to see the actual node. Which can be very tedious. I am constantly having to hit zoom to selection after creation of an execution node which sadly breaks my flow.

Thanks for your consideration!

**Comment by fpwong** [comment]
Hi Dvoya, I had actually prototyped this feature a long time ago but never got to fully implementing it. 

Will add this to the next update, keep the ideas coming! 👍

**Comment by fpwong** [comment]
Added in 3.2.0
