### ISSUE TITLE
[Feature Requests] Functions private by default

### ISSUE THREAD

**Issue by organicFoil** [fpwong/BlueprintAssistWiki#49]
![image](https://user-images.githubusercontent.com/13570355/131481574-d131b482-6d53-4187-af19-f6f02d4f0ecb.png)
As variable, but for functions. Thank you

**Comment by fpwong** [comment]
Hi organicFoil, I will look into this. I think the workflow is slightly different compared to variables but hopefully shouldn't be too hard to implement this.

**Comment by fpwong** [comment]
Added in 3.2.0
