### ISSUE TITLE
Using BlueprintAssist with plugin "Logic Driver - State Machine" cause crash

### ISSUE THREAD

**Issue by parasetamon** [fpwong/BlueprintAssistWiki#5]
Hi, I'm using the plugin "Logic Driver - State Machine" with BlueprintAssist (Here is the link : [Logic Driver - State Machine](https://www.unrealengine.com/marketplace/en-US/slug/logic-driver-state-machine-blueprint-editor))

Sometimes when I open the graph inside the state change line (lines between each state), the editor will crash with this log : 

```
Unhandled exception

UE4Editor_BlueprintAssist!FBAGraphHandler::UpdateNodesRequiringFormatting() [d:\build\++portal+dev-marketplace+full\sync\localbuilds\plugintemp\hostproject\plugins\blueprintassist\source\blueprintassist\private\blueprintassistgraphhandler.cpp:974]
UE4Editor_BlueprintAssist!FBAGraphHandler::Tick() [d:\build\++portal+dev-marketplace+full\sync\localbuilds\plugintemp\hostproject\plugins\blueprintassist\source\blueprintassist\private\blueprintassistgraphhandler.cpp:308]
UE4Editor_BlueprintAssist!FBATabHandler::Tick() [d:\build\++portal+dev-marketplace+full\sync\localbuilds\plugintemp\hostproject\plugins\blueprintassist\source\blueprintassist\private\blueprintassisttabhandler.cpp:47]
UE4Editor_BlueprintAssist!FBAInputProcessor::Tick() [d:\build\++portal+dev-marketplace+full\sync\localbuilds\plugintemp\hostproject\plugins\blueprintassist\source\blueprintassist\private\blueprintassistinputprocessor.cpp:311]
UE4Editor_Slate!FSlateApplication::InputPreProcessorsHelper::Tick() [d:\build\++ue4\sync\engine\source\runtime\slate\private\framework\application\slateapplication.cpp:7520]
UE4Editor_Slate!FSlateApplication::FinishedInputThisFrame() [d:\build\++ue4\sync\engine\source\runtime\slate\private\framework\application\slateapplication.cpp:1604]
UE4Editor!FEngineLoop::Tick() [d:\build\++ue4\sync\engine\source\runtime\launch\private\launchengineloop.cpp:3945]
UE4Editor!GuardedMain() [d:\build\++ue4\sync\engine\source\runtime\launch\private\launch.cpp:168]
UE4Editor!GuardedMainWrapper() [d:\build\++ue4\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:145]
UE4Editor!WinMain() [d:\build\++ue4\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:275]
UE4Editor!__scrt_common_main_seh() [d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll
```

It would be great if solving this bug can prevent any bugs related in the future.

Thank you in advance.

**Comment by fpwong** [comment]
Hi parasetamon, 

I have fixed an issue related to the crash you provided. But I am not sure if the issue I just fixed is actually the issue you encountered. 

The issue I just fixed should occur when you run the format all function (CTRL + R). So it should not crash when you open the graph. Do you perhaps have either the **Always Format All** or **Auto Position Event Nodes** settings set to true?

Just in case, could you provide a screenshot of what your graph inside the state change line looks like?

**Comment by parasetamon** [comment]
Hi @fpwong ,

I tested and can confirm that after disable Always Format All and Auto Position Event Nodes, the editor will not automatically crash, but it still crashes when pressed ctrl + R to reformat all event node only.

Here is the image of the graph you've asked.
![Graph](https://user-images.githubusercontent.com/7240153/61468230-1e083e00-a9a7-11e9-86e9-e2f6fa415628.png)

Thank you for your kindly support, keep up the good work.

**Comment by parasetamon** [comment]
Hi @fpwong,

After an update, I didn't catch any crash anymore.

I'll close this thread, Thank you.
