### ISSUE TITLE
[Crash] Edit Details shortcut key menu crashes on control rig node in anim graph

### ISSUE THREAD

**Issue by Dvoya** [fpwong/BlueprintAssistWiki#50]
Using the edit detail shortcut menu to while the control rig node is selected in 4.26.2 with the control rig plugin enabled in the anim graph causes a crash. 

Assertion failed: IsValid() [File:D:\RocketSync\4.26.0-14830424+++UE4+Release-4.26\Working\Engine\Source\Runtime\Core\Public\Templates/SharedPointer.h] [Line: 890]

UE4Editor_Core
UE4Editor_Core
UE4Editor_BlueprintAssist!SEditDetailsMenu::InitListItems() [D:\build\++Portal\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\BlueprintAssist\Source\BlueprintAssist\BlueprintAssistWidgets\EditDetailsMenu.cpp:44]
UE4Editor_BlueprintAssist!TBaseSPMethodDelegateInstance<0,SEditDetailsMenu,0,void __cdecl(TArray<TSharedPtr<FEditDetailsStruct,0>,TSizedDefaultAllocator<32> > &),FDefaultDelegateUserPolicy>::Execute() [D:\RocketSync\4.26.0-14830424+++UE4+Release-4.26\Working\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:290]
UE4Editor_BlueprintAssist!SBAFilteredList<TSharedPtr<FEditDetailsStruct,0> >::Construct() [D:\build\++Portal\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\BlueprintAssist\Source\BlueprintAssist\BlueprintAssistWidgets\BAFilteredList.cpp:24]
UE4Editor_BlueprintAssist!TDecl<SBAFilteredList<TSharedPtr<FEditDetailsStruct,0> >,RequiredArgs::T0RequiredArgs>::operator<<=() [D:\RocketSync\4.26.0-14830424+++UE4+Release-4.26\Working\Engine\Source\Runtime\SlateCore\Public\Widgets\DeclarativeSyntaxSupport.h:1122]
UE4Editor_BlueprintAssist!SEditDetailsMenu::Construct() [D:\build\++Portal\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\BlueprintAssist\Source\BlueprintAssist\BlueprintAssistWidgets\EditDetailsMenu.cpp:18]
UE4Editor_BlueprintAssist!TDecl<SEditDetailsMenu,RequiredArgs::T0RequiredArgs>::operator<<=() [D:\RocketSync\4.26.0-14830424+++UE4+Release-4.26\Working\Engine\Source\Runtime\SlateCore\Public\Widgets\DeclarativeSyntaxSupport.h:1122]
UE4Editor_BlueprintAssist!FBAInputProcessor::OpenEditDetailsMenu() [D:\build\++Portal\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistInputProcessor.cpp:1311]
UE4Editor_BlueprintAssist!TBaseRawMethodDelegateInstance<0,FBAInputProcessor,void __cdecl(void),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [D:\RocketSync\4.26.0-14830424+++UE4+Release-4.26\Working\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:469]
UE4Editor_Slate
UE4Editor_Slate
UE4Editor_BlueprintAssist!FBAInputProcessor::HandleKeyDownEvent() [D:\build\++Portal\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistInputProcessor.cpp:381]
UE4Editor_Slate
UE4Editor_Slate
UE4Editor_Slate
UE4Editor_ApplicationCore
UE4Editor_ApplicationCore
UE4Editor_ApplicationCore
UE4Editor_ApplicationCore

**Comment by fpwong** [comment]
Thanks Dvoya, I was able to replicate this crash. Will be fixed in the next update.

**Comment by fpwong** [comment]
Fixed in 3.0.0
