### ISSUE TITLE
Cant build solution after 3.2.0 update

### ISSUE THREAD

**Issue by organicFoil** [fpwong/BlueprintAssistWiki#51]
![image](https://user-images.githubusercontent.com/13570355/134317081-31e2e92e-c40b-4383-9ad8-771687dd5bd1.png)

VS2019 (updated version) error
`MSB3073	The command ""C:\Program Files\Epic Games\UE_4.26\Engine\Build\BatchFiles\Build.bat" MyGameEditor Win64 Development -Project="C:\Projects\MyGame\MyGame.uproject" -WaitMutex -FromMsBuild" exited with code 6.	MyGame	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.MakeFile.Targets	`

Removing the plugin solves the problem

**Comment by fpwong** [comment]
Hi organicFoil, some questions: 

* Are you building the plugin manually or did you install it into the engine?
* Was there any other info about what cause the build to fail?

I'll have a look into this. Perhaps for now could you try to disable the plugin from building outside the editor. You can do so by WhiteListing it in your MyGame.uproject.

See this link: https://github.com/fpwong/BlueprintAssistWiki/wiki/FAQ#stop-any-editor-plugin-from-building--compiling-when-packaging

Let me know if that works for you

**Comment by organicFoil** [comment]
Hello!
Firstly, sorry for bad english and thank you for amazing plugin

Secondly, my answers:
1. Plugin installed in engine
2. WhiteListing didnt help, only disabling works

3. Logs from buildingTool:

LogCompile: Error: An explicit Category specifier is required for any
> property exposed to the editor or Blueprints in an Engine module.
> LogCompile: Error: An explicit Category specifier is required for any
> property exposed to the editor or Blueprints in an Engine module.
> LogCompile: Error: An explicit Category specifier is required for any
> property exposed to the editor or Blueprints in an Engine module.
> LogCompile: Error: An explicit Category specifier is required for any
> property exposed to the editor or Blueprints in an Engine module.
> LogCompile: Error: An explicit Category specifier is required for any
> property exposed to the editor or Blueprints in an Engine module.
> [LogCompile: Error: An explicit Category specifier is required for any
> property exposed to the editor or Blueprints in an Engine module.
> LogCompile: Error: An explicit Category specifier is required for any
> property exposed to the editor or Blueprints in an Engine module.
> LogCompile: Error: An explicit Category specifier is required for any
> property exposed to the editor or Blueprints in an Engine module.
> LogCompile: Generating code for module 'BlueprintAssist'
> LogCompile: Success: Parsed 720 line(s), 173 statement(s) in 0.00 secs.



ср, 22 сент. 2021 г. в 17:15, fpwong ***@***.***>:

**Comment by organicFoil** [comment]
1. Plugin installed in engine
2. WhiteListing didnt help, only disabling works

3. Logs from buildingTool:

LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
LogCompile: Generating code for module 'BlueprintAssist'
LogCompile: Success: Parsed 720 line(s), 173 statement(s) in 0.00 secs.

**Comment by organicFoil** [comment]
1. Plugin installed in engine
2. WhiteListing didnt help, only disabling works

3. Logs from buildingTool:

```
LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
LogCompile: Generating code for module 'BlueprintAssist'
LogCompile: Success: Parsed 720 line(s), 173 statement(s) in 0.00 secs.
```
sorry for little mess

**Comment by fpwong** [comment]
Sorry about this crash, the update is out now. Let me know if that fixed it.

**Comment by organicFoil** [comment]
Fixed!
