### ISSUE TITLE
(3.2.2) Blueprint Formatting support for Logic Driver plugin.

### ISSUE THREAD

**Issue by yuanb36** [fpwong/BlueprintAssistWiki#53]
Hello.

 After updated to 3.2.2, I noticed that Blueprint Formatting does not work for Logic Driver graphs anymore. It used to work in 3.1.5 to 3.2.1 as I remember.

Auto Formatting worked in those graph before. Those graphs are just assembled by normal blueprint nodes.

State Machine Root Graph
![StateMachine Root Graph](https://user-images.githubusercontent.com/11003036/134755417-18303ca1-7eb7-4d68-ba1a-c3f2017e12f4.png)

State Machine State Intermediate Graph
![StateMachine State Intermediate Graph](https://user-images.githubusercontent.com/11003036/134755497-6fa49bff-27e7-482f-b1d4-52f517dafaec.png)

State Machine Transition Intermediate Graph
![StateMachine Transition Intermediate Graph](https://user-images.githubusercontent.com/11003036/134755498-055c8190-43fe-4a3d-ad4d-8dcbc86b892b.png)

State Machine Reference Intermediate Graph
![StateMachine Reference Intermediate Graph](https://user-images.githubusercontent.com/11003036/134755496-016587dc-ca87-41fe-92a9-d99d4f1611cb.png)

Could you please make it work again in those graphs? 
Blueprint Assist and Logic Driver are both great plugins,  and I just can't live without them.

**Comment by fpwong** [comment]
Hi, one of the changes recently was to improve the way that other graph types would be supported by the plugin. The old method I was using could potentially cause issues. However considering that no one actually reported having issues with it, I may implement the old method back as an option so you don't need to manually add all these graphs.

For now you can follow this to add in any graphs you would like blueprint formatting: 
https://www.youtube.com/watch?v=1wSNJyQWARo

**Comment by yuanb36** [comment]
Hello.

I followed the FAQ instructions, it works like a charm! 
Thank you very much!

![BlueprintAssist Graph Settings](https://user-images.githubusercontent.com/11003036/134759488-e938d94d-1229-45cc-b77c-31e8809a1f2e.png)
