### ISSUE TITLE
Odd wire placement.

### ISSUE THREAD

**Issue by Troto** [fpwong/BlueprintAssistWiki#54]
![image](https://user-images.githubusercontent.com/7268208/136144038-b6fcff86-9ba7-445a-a779-3ede3f0e6fb9.png)

We have this sort of wire placement in a few places in our codebase. Is there some sort of setting that's causing this or it's just the complex nature of the wiring? Either way something a little more readable would be nice.

**Comment by fpwong** [comment]
Yes this is just how the wiring works at the moment. In fact I happen to have been working on improving to this for the past couple of days, hopefully it will be ready soon.

**Comment by Troto** [comment]
Ah OK, thanks for the fast response. I trust that improvements are on their way then and I'll close this.
