### ISSUE TITLE
Comments no longer spacing

### ISSUE THREAD

**Issue by Troto** [fpwong/BlueprintAssistWiki#55]
![image](https://user-images.githubusercontent.com/7268208/136145577-ecf7829b-5f1c-4428-8407-14bf3e80ae93.png)

I saw in the patch notes that comments on parameters aren't affected by apply comment padding anymore. So there is no way to prevent these overlapping now?

**Comment by fpwong** [comment]
I redid the entire system around working with comments so I thought it would be better to release the nodes first and then fix the parameters next. This is also planned for the next update. Sadly there is no solution for this in place right now.

**Comment by Troto** [comment]
Understood, thanks for your awesome work!
