### ISSUE TITLE
Incorrect Collapse To Function

### ISSUE THREAD

**Issue by visualcortex** [fpwong/BlueprintAssistWiki#58]
Hi there,

- Please check the graph in the attached image.
- Collapse PrintString to a function.
- BeginPlay is now connected to the new function though PrintString has not been connected.

![cap_Blueprint Assist - Incorrect Collapse To Function_00_00_00_01](https://user-images.githubusercontent.com/1764223/137599759-490ad6e5-0b87-412f-9fc2-bffae7f48a60.jpg)
![cap_Blueprint Assist - Incorrect Collapse To Function_00_00_06_02](https://user-images.githubusercontent.com/1764223/137599762-cacc25d8-7306-43a3-9bae-0ebfe64dc9ab.jpg)

**Comment by fpwong** [comment]
Thanks visualcortex, this will be fixed in the next update.

**Comment by fpwong** [comment]
This should be fixed in 3.2.3
