### ISSUE TITLE
Enable shift dragging not seeming to work in 4.27

### ISSUE THREAD

**Issue by Dvoya** [fpwong/BlueprintAssistWiki#60]
Can't seem to get the shift drag function to work! Unsure why as I do remember it working in a previous version. I'm on 4.27, the most recent version of blueprint assist.

**Comment by fpwong** [comment]
Ahh... while cleaning up the code I flipped an if statement -.-
Will be fixed in the next update!

**Comment by fpwong** [comment]
This should be fixed in 3.2.3
