### ISSUE TITLE
Enhanced input nodes not recognized by "go to symbol" menu

### ISSUE THREAD

**Issue by Dvoya** [fpwong/BlueprintAssistWiki#61]
I can't see to have it recognize the nodes produced by enhanced input on 4.27. 
![image](https://user-images.githubusercontent.com/60451976/140978088-865d13ab-6e44-48b9-8429-f3f575fc8f93.png)

**Comment by fpwong** [comment]
Thanks for the report, this will be fixed in the next update

**Comment by fpwong** [comment]
This should be fixed in 3.2.3
