### ISSUE TITLE
Private functions in Blueprint Interfaces

### ISSUE THREAD

**Issue by organicFoil** [fpwong/BlueprintAssistWiki#64]
When plugin option "Default function access specifier" set to Private, functions in blueprint interfaces also creates as private.
I can't change their specifier. This blocks interface functions usage for me.
Blueprint Interface functions always must be public

**Comment by fpwong** [comment]
Sorry about that, I'm sure this was a huge pain to figure out. Will be fixed in the next update (~1-2 days from now).

**Comment by fpwong** [comment]
Fixed in 3.2.7
