### ISSUE TITLE
Crash when adding a variable

### ISSUE THREAD

**Issue by tshabi8** [fpwong/BlueprintAssistWiki#66]
Just had a crash when tried to add a variable to actor BP:
4.26.2 latest version of plugin

LoginId:0a082a664416f3db62f92698b3809295
EpicAccountId:68cd76207d9645f5bbcab58f22feaa12

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0xffffffffffffffff

UE4Editor_Core!rml::internal::Block::findObjectSize() [d:\dev-enterprise\engine\source\thirdparty\inteltbb\inteltbb-2019u8\src\tbbmalloc\frontend.cpp:2139]
UE4Editor_Core!rml::internal::reallocAligned() [d:\dev-enterprise\engine\source\thirdparty\inteltbb\inteltbb-2019u8\src\tbbmalloc\frontend.cpp:2414]
UE4Editor_Core!scalable_realloc() [d:\dev-enterprise\engine\source\thirdparty\inteltbb\inteltbb-2019u8\src\tbbmalloc\frontend.cpp:2993]
UE4Editor_Core!FMallocTBB::Realloc() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Core\Private\HAL\MallocTBB.cpp:138]
UE4Editor_Core!FMemory::Realloc() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Core\Public\HAL\FMemory.inl:56]
UE4Editor_BlueprintAssist!TArray<FBAVariableDescription,TSizedDefaultAllocator<32> >::ResizeTo() [D:\RocketSync\4.26.0-14830424+++UE4+Release-4.26\Working\Engine\Source\Runtime\Core\Public\Containers\Array.h:2580]
UE4Editor_BlueprintAssist!FBABlueprintHandler::SetLastVariables() [D:\build\++Portal\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistBlueprintHandler.cpp:108]
UE4Editor_BlueprintAssist!FBABlueprintHandler::OnBlueprintChanged() [D:\build\++Portal\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistBlueprintHandler.cpp:212]
UE4Editor_BlueprintAssist!TBaseRawMethodDelegateInstance<0,FBABlueprintHandler,void __cdecl(UBlueprint *),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [D:\RocketSync\4.26.0-14830424+++UE4+Release-4.26\Working\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:469]
UE4Editor_Engine!TMulticastDelegate<void __cdecl(UBlueprint *),FDefaultDelegateUserPolicy>::Broadcast() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Core\Public\Delegates\DelegateSignatureImpl.inl:955]
UE4Editor_UnrealEd!FBlueprintEditorUtils::MarkBlueprintAsStructurallyModified() [D:\Build\++UE4\Sync\Engine\Source\Editor\UnrealEd\Private\Kismet2\BlueprintEditorUtils.cpp:2080]
UE4Editor_UnrealEd!FBlueprintEditorUtils::AddMemberVariable() [D:\Build\++UE4\Sync\Engine\Source\Editor\UnrealEd\Private\Kismet2\BlueprintEditorUtils.cpp:4714]
UE4Editor_Kismet!FBlueprintEditor::OnAddNewVariable() [D:\Build\++UE4\Sync\Engine\Source\Editor\Kismet\Private\BlueprintEditor.cpp:8664]
UE4Editor_Kismet!TBaseSPMethodDelegateInstance<0,FBlueprintEditor,0,void __cdecl(void),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:307]
UE4Editor_Slate!FUICommandList::ExecuteAction() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Slate\Private\Framework\Commands\UICommandList.cpp:102]
UE4Editor_Kismet!SMyBlueprint::OnAddButtonClickedOnSection() [D:\Build\++UE4\Sync\Engine\Source\Editor\Kismet\Private\SMyBlueprint.cpp:869]
UE4Editor_Kismet!TBaseSPMethodDelegateInstance<0,SMyBlueprint,0,FReply __cdecl(void),FDefaultDelegateUserPolicy,int>::Execute() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:290]
UE4Editor_Slate!SButton::ExecuteOnClick() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Slate\Private\Widgets\Input\SButton.cpp:385]
UE4Editor_Slate!SButton::OnMouseButtonUp() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Slate\Private\Widgets\Input\SButton.cpp:304]
UE4Editor_Slate!FEventRouter::Route<FReply,FEventRouter::FToLeafmostPolicy,FPointerEvent,<lambda_cc5aea9e7377b04ce85c30c65ec3889b> >() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Slate\Private\Framework\Application\SlateApplication.cpp:378]
UE4Editor_Slate!FSlateApplication::RoutePointerUpEvent() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Slate\Private\Framework\Application\SlateApplication.cpp:4815]
UE4Editor_Slate!FSlateApplication::ProcessMouseButtonUpEvent() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Slate\Private\Framework\Application\SlateApplication.cpp:5356]
UE4Editor_Slate!FSlateApplication::OnMouseUp() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Slate\Private\Framework\Application\SlateApplication.cpp:5321]
UE4Editor_ApplicationCore!FWindowsApplication::ProcessDeferredMessage() [D:\Build\++UE4\Sync\Engine\Source\Runtime\ApplicationCore\Private\Windows\WindowsApplication.cpp:2178]
UE4Editor_ApplicationCore!FWindowsApplication::DeferMessage() [D:\Build\++UE4\Sync\Engine\Source\Runtime\ApplicationCore\Private\Windows\WindowsApplication.cpp:2642]
UE4Editor_ApplicationCore!FWindowsApplication::ProcessMessage() [D:\Build\++UE4\Sync\Engine\Source\Runtime\ApplicationCore\Private\Windows\WindowsApplication.cpp:1046]
UE4Editor_ApplicationCore!FWindowsApplication::AppWndProc() [D:\Build\++UE4\Sync\Engine\Source\Runtime\ApplicationCore\Private\Windows\WindowsApplication.cpp:878]
user32
user32
UE4Editor_ApplicationCore!FWindowsPlatformApplicationMisc::PumpMessages() [D:\Build\++UE4\Sync\Engine\Source\Runtime\ApplicationCore\Private\Windows\WindowsPlatformApplicationMisc.cpp:130]
UE4Editor!FEngineLoop::Tick() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:4748]
UE4Editor!GuardedMain() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Launch\Private\Launch.cpp:169]
UE4Editor!GuardedMainWrapper() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:137]
UE4Editor!WinMain() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:268]
UE4Editor!__scrt_common_main_seh() [d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

**Comment by fpwong** [comment]
Hi tsabi8, sorry for the late reply. I do believe this is a similar issue as #68.

Please try enabling the setting `UseUObjects` and making sure your plugin is up to date (3.2.8).

I will leave this issue open for a while in case others have the same crash log.

**Comment by fpwong** [comment]
Closing this issue as `UseUObjects` enabled is now the default behaviour (as of 3.2.9).
