### ISSUE TITLE
Editor crash

### ISSUE THREAD

**Issue by organicFoil** [fpwong/BlueprintAssistWiki#68]
`Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0xffffffffffffffff

UE4Editor_BlueprintAssist!TSet<TTuple<FGuid,int>,TDefaultMapHashableKeyFuncs<FGuid,int,0>,FDefaultSetAllocator>::Emplace<TPairInitializer<FGuid const &,int const &> >() [D:\RocketSync\4.27.0-17155196+++UE4+Release-4.27\Working\Engine\Source\Runtime\Core\Public\Containers\Set.h:667]
UE4Editor_BlueprintAssist!FBABlueprintHandler::OnBlueprintChanged() [D:\build\++Portal\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistBlueprintHandler.cpp:181]
UE4Editor_BlueprintAssist!TBaseRawMethodDelegateInstance<0,FBABlueprintHandler,void __cdecl(UBlueprint *),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [D:\RocketSync\4.27.0-17155196+++UE4+Release-4.27\Working\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:469]
UE4Editor_Engine
UE4Editor_Kismet
UE4Editor_Kismet
UE4Editor_UnrealEd
UE4Editor_Kismet
UE4Editor_Kismet
UE4Editor_Slate
UE4Editor_Slate
UE4Editor_Slate
UE4Editor_Slate
UE4Editor_Slate
UE4Editor_Slate
UE4Editor_Slate
UE4Editor_Slate
UE4Editor_Slate
UE4Editor_ApplicationCore
UE4Editor_ApplicationCore
UE4Editor_ApplicationCore
UE4Editor_ApplicationCore
user32
user32
UE4Editor_ApplicationCore
UE4Editor
UE4Editor
UE4Editor
UE4Editor
UE4Editor
UE4Editor
kernel32
ntdll`

Happens when trying to compile various blueprints. Can't find out a more definite pattern

**Comment by fpwong** [comment]
Hi organicfoil, in a recent update (3.2.7) the setting `UseUObjects` was set to true by default. This setting should have fixed this crash. Make sure the setting is enabled and the plugin is up to date (currently on 3.2.8). 

Please let me know if you encounter this issue again with the setting enabled.

**Comment by fpwong** [comment]
Closing this issue as `UseUObjects` enabled is now the default behaviour (as of 3.2.9).
