### ISSUE TITLE
Strange Crash, unable to reproduce, but perhaps you can get something from the logs.

### ISSUE THREAD

**Issue by Dvoya** [fpwong/BlueprintAssistWiki#69]
Just got this error log while working in 4.27. It happened while working in a widget blueprint.
I just finished editing a comment, Went to compile and save after formatting. I did it rather quick, I can't really reproduce it, but here's my logs in case you can get something from it. 

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0xffffffffffffffff

UE4Editor_BlueprintAssist!TSet<TTuple<FGuid,int>,TDefaultMapHashableKeyFuncs<FGuid,int,0>,FDefaultSetAllocator>::Emplace<TPairInitializer<FGuid const &,int const &> >() [D:\RocketSync\4.27.0-17155196+++UE4+Release-4.27\Working\Engine\Source\Runtime\Core\Public\Containers\Set.h:667]
UE4Editor_BlueprintAssist!FBABlueprintHandler::OnBlueprintChanged() [D:\build\++Portal\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistBlueprintHandler.cpp:181]
UE4Editor_BlueprintAssist!TBaseRawMethodDelegateInstance<0,FBABlueprintHandler,void __cdecl(UBlueprint *),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [D:\RocketSync\4.27.0-17155196+++UE4+Release-4.27\Working\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:469]
UE4Editor_Engine
UE4Editor_Kismet
UE4Editor_Kismet
UE4Editor_UnrealEd
UE4Editor_Kismet
UE4Editor_Kismet
UE4Editor_Slate
UE4Editor_Slate
UE4Editor_UnrealEd
UE4Editor_UnrealEd
UE4Editor_Slate
UE4Editor_Slate
UE4Editor_Slate
UE4Editor_ApplicationCore
UE4Editor_ApplicationCore
UE4Editor_ApplicationCore
UE4Editor_ApplicationCore
user32
user32
InkObj
atlthunk
user32
user32
UE4Editor_ApplicationCore
UE4Editor
UE4Editor
UE4Editor
UE4Editor
UE4Editor
UE4Editor
kernel32
ntdll

**Comment by fpwong** [comment]
Please see isssue #68 and let me know if you ever encounter this issue again with the new setting on.
