### ISSUE TITLE
Request: Disabling AutoZoom on selection outside Viewport

### ISSUE THREAD

**Issue by TheBanishingOfMosquito** [fpwong/BlueprintAssistWiki#71]
![Option4DisableAutoZoom](https://user-images.githubusercontent.com/65665572/151659076-ef51547e-26ac-4e15-88da-ce3db210061f.gif)

Is there an option for _DisablingAutozoom_ when node is outside viewport - without enabling _Globally DisableAutoFormatting_-,
And if not can it be added?

**Comment by fpwong** [comment]
Hi, this was an unintended behaviour in version 3.2.9. Please update the plugin and this should not happen anymore.
