### ISSUE TITLE
WorkflowTools. Shortcut. Nothing happening

### ISSUE THREAD

**Issue by TheBanishingOfMosquito** [fpwong/BlueprintAssistWiki#72]
![SwitchworkflowMode](https://user-images.githubusercontent.com/65665572/151665867-3831ddb6-d6f9-4755-b54d-11cff8db6226.gif)

There is no menu popping up.

**Comment by fpwong** [comment]
Hi, it looks like this is a regular blueprint graph? Let me know if it is not.

The workflow switcher only works for certain graphs which have workflow tabs in the top right (mainly the Animation BP and the Widget BP). 

Example below: the WBP has designer / graph workflows

![Capture](https://user-images.githubusercontent.com/7879618/151683563-67f27948-2c3a-43f6-a9ad-66f8ff8e11cf.JPG)


It is hard to tell right now when these types of commands are not applicable, in the future I will make a message pop up when they don't apply.

**Comment by TheBanishingOfMosquito** [comment]
Yes you are correct I used it for the wrong kind of BP. ok now I understand this is for widget BP
