### ISSUE TITLE
Request: AutoFormattingBehaviour/OnlyFormatTheSwapNodeLeft&Right

### ISSUE THREAD

**Issue by TheBanishingOfMosquito** [fpwong/BlueprintAssistWiki#74]
Can you add a checkbox in the pluginPreference. So that we can toggle the auto formatting only for the SwapNodesLeftRight ShortcutFeature? Similar to this one:
![image](https://user-images.githubusercontent.com/65665572/151667105-9c3b36cc-11c1-4771-a8dd-331bb4003eec.png)

**Comment by fpwong** [comment]
Hi, I have thought about adding more details like this for each command but I think it would become too messy.

I'm guessing you would like to enable some sort of formatting for after you swap nodes, because otherwise it messes up the wires? A workaround I can think of is: when auto formatting is disabled, simply swap the position of the two nodes.

Let me know if this improvement would fix your issue.

**Comment by TheBanishingOfMosquito** [comment]
In the default settings the _swap nodes shortcut_ will swap not only the wires but also the positions. I like it. Its saving mouse clicks. If _auto format is turned off_. Then it will only swap the wires. Which is ok bc as you mentioned we can drag the nodes with mouse cursor. 

Often times I prefer to disable the autoformating feature bc, even not using the _FormatingShorcuts_, after using the _SwapNodes shortcut_, it will autoformat **everything** and pushes everything together. Too cloudy for me. Well  in the train its  nice when not using mouse. But at your workstation its feels more relaxing to be able to stretch the node graph apart and keep it like that. For my eyes its easier to follow and remember ideas, if the graph is keeping a certain wideness. 

Maybe there is already an option for that, and I didnt notice it yet. As for now I guess I will workaround that. Using custom shortcut for Disabling Formatting & enabling Formatting.

**Comment by fpwong** [comment]
Please try out the behaviour when auto-formatting is disabled in 3.2.12

**Comment by TheBanishingOfMosquito** [comment]
![update](https://user-images.githubusercontent.com/65665572/152639994-1f77f422-bd52-402f-bdeb-ac1b27a32f6b.gif)

Sweeeet. Merci ! It works like a charm :)

**Comment by fpwong** [comment]
👍
