### ISSUE TITLE
Crashing editor

### ISSUE THREAD

**Issue by Subressor** [fpwong/BlueprintAssistWiki#79]
![image](https://user-images.githubusercontent.com/40392247/163729199-cf605585-7082-4a76-9929-6080b24d6757.png)
Editor crashing when using mesh editor in Static mesh. Also other crashes

**Comment by fpwong** [comment]
Hi Subressor, the crash when opening the Mesh Editing tab issue should have been fixed in the latest update (3.2.15), please check you are on the latest version.
