### ISSUE TITLE
New Crash With Latest Marketplace Update

### ISSUE THREAD

**Issue by Sikotik13** [fpwong/BlueprintAssistWiki#80]
Installed the latest update for UE 5.0.2 from the marketplace this morning, and now on opening a material graph, the editor crashes. Short log, at least:

```
Assertion failed: IsValid() [File:D:\RocketSync\5.0.0-19505902+++UE5+Release-5.0\Working\Engine\Source\Runtime\Core\Public\Templates\SharedPointer.h] [Line: 1074]

UnrealEditor_BlueprintAssist!FBAGraphHandler::SetSelectedPin() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistGraphHandler.cpp:2297]
UnrealEditor_BlueprintAssist!FBAGraphHandler::OnSelectionChanged() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistGraphHandler.cpp:282]
UnrealEditor_BlueprintAssist!FBAGraphHandler::Tick() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistGraphHandler.cpp:467]
UnrealEditor_BlueprintAssist!FBATabHandler::Tick() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistTabHandler.cpp:50]
UnrealEditor_BlueprintAssist!FBAInputProcessor::Tick() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistInputProcessor.cpp:360]
UnrealEditor_Slate
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
kernel32
ntdll
```

This log was on a creating a new material and attempting to open it. The crash happens as soon as the material graph opens.

**Comment by Sikotik13** [comment]
Not sure how related it might be, but I just had the crash repeat on trying to add a function call from a context menu in a scene component blueprint. Same error log. Since it may or may not matter, for this one, I was trying to use a specific function from a plugin, it didn't do it before with anything else, so it may just be random, will attempt to repeat it, if possible.

**Comment by Sikotik13** [comment]
Nope, just added that same call, in the same blueprint (just reopened the project and asset post-crash). Worked fine this time. Weird error, but hopefully it helps in some way that the crash can be provoked randomly?

**Comment by fpwong** [comment]
Sorry about this, I believe I have fixed this now. You can download the hotfix here and replace the BlueprintAssist plugin folder. Located at `Epic Games/UE_5.0/Engine/Plugins/Marketplace/BlueprintAssist`: 
* [4.26](https://drive.google.com/file/d/1lLEMu2OS-i7OfCkHlk7iTk4HNGCjAVW6/view?usp=sharing)
* [4.27](https://drive.google.com/file/d/14KXGb7fBw3rrqhGSGdtKX85kOwqAqzs8/view?usp=sharing)
* [5.00](https://drive.google.com/file/d/1rKm_XuvgZJ7oDLE5ChOqklsYmuKkbGT1/view?usp=sharing)

Let me know if you do encounter this again. This update should be out on the marketplace in a couple of days.

**Comment by Sikotik13** [comment]
It definitely at least seems fixed for me. Kudos!

**Comment by fpwong** [comment]
Thanks for reporting this so quickly @Sikotik13. Keeping this issue open for visibility in case others look here for a solution. I will close it once the update is live on the marketplace.

**Comment by joergselters** [comment]
Same Problem.

LoginId:71778d474e533a3fc3e64c8d431f97ae
EpicAccountId:3fcbffaee0a64f928c45d11d213b83b8

Assertion failed: IsValid() [File:D:\RocketSync\5.0.0-19505902+++UE5+Release-5.0\Working\Engine\Source\Runtime\Core\Public\Templates\SharedPointer.h] [Line: 1074]

UnrealEditor_BlueprintAssist!FBAGraphHandler::SetSelectedPin() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistGraphHandler.cpp:2297]
UnrealEditor_BlueprintAssist!FBAGraphHandler::OnSelectionChanged() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistGraphHandler.cpp:282]
UnrealEditor_BlueprintAssist!FBAGraphHandler::Tick() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistGraphHandler.cpp:467]
UnrealEditor_BlueprintAssist!FBATabHandler::Tick() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistTabHandler.cpp:50]
UnrealEditor_BlueprintAssist!FBAInputProcessor::Tick() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistInputProcessor.cpp:360]
UnrealEditor_Slate!FSlateApplication::FinishedInputThisFrame() [D:\build\++UE5\Sync\Engine\Source\Runtime\Slate\Private\Framework\Application\SlateApplication.cpp:1376]
UnrealEditor!FEngineLoop::Tick() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:5199]
UnrealEditor!GuardedMain() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Launch.cpp:183]
UnrealEditor!GuardedMainWrapper() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:147]
UnrealEditor!LaunchWindowsStartup() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:283]
UnrealEditor!WinMain() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:330]
UnrealEditor!__scrt_common_main_seh() [d:\a01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

**Comment by CoolOppo** [comment]
@joergselters you need to do [what he said a couple comments above yours](https://github.com/fpwong/BlueprintAssistWiki/issues/80#issuecomment-1149469411)

**Comment by fpwong** [comment]
Update 3.3.1 is out on the marketplace now

**Comment by SGMike** [comment]
Still getting this after the marketplace update

**Comment by fpwong** [comment]
@SGMike Do you remember what caused the crash to happen? Was it on opening the material graph or during some other event?

**Comment by SGMike** [comment]
Unfortunately I dont know an exact repro. I was basically just working in UMG widget blueprints and it would crash every 20 minutes or so. I can play around with it some more tomorrow and maybe get an exact reproduction.

**Comment by SGMike** [comment]
@fpwong I haven't run into the issue today, I ended up having some issues with my binaries, after cleaning out the binaries and intermediate folders and it seems like that might have been my issue locally, sorry about that!

**Comment by fpwong** [comment]
@SGMike That's great, let me know if you find any other issues
