### ISSUE TITLE
Visual bug in getter node

### ISSUE THREAD

**Issue by organicFoil** [fpwong/BlueprintAssistWiki#82]
![image](https://user-images.githubusercontent.com/13570355/172593652-09961131-d8cf-438b-b4b4-eeb94cf5aa77.png)
Top: with enabled plugin
Bottom: with disabled plugin

Plugin version: 3.3.0
Engine version: 4.27.2-18319896

**Comment by fpwong** [comment]
Ahh I forgot about this case. I've changed the way the pins are highlighted but reused the `PinHighlightColor` setting. So if you had changed that setting in the past it wouldn't have updated to the suggested value

Try setting the `PinHighlightColor` to the default of `(0.6, 0.6, 0.6, 0.33)`
