### ISSUE TITLE
drag multiple node bug

### ISSUE THREAD

**Issue by pasunna** [fpwong/BlueprintAssistWiki#85]
when drag multiple node at the same time in UE5
only one node that mouse on is follow
this happen after install this plugin

**Comment by fpwong** [comment]
Hi @pasunna. There are only two setting related to mouse dragging:
* `Additional Drag Nodes Chords`: bind keys to drag around nodes
* `Group Movement Chords`: when these keys are held you move all connected nodes around

Could you try removing these and let me know if that helps?
