### ISSUE TITLE
Compile Failures

### ISSUE THREAD

**Issue by Edstub207** [fpwong/BlueprintAssistWiki#86]
Hello!

This plugin has *a lot* of compile failures due to missing includes when using a Non-PCH Build (And non-unity) config. 

Is there a plan for these getting resolved?

**Comment by fpwong** [comment]
Hi, I will try to fix these in the next update, definitely seeing seeing *many* compile errors with these settings. And just to make sure we have the same build settings they are as below?

```
PCHUsage = ModuleRules.PCHUsageMode.NoPCHs;
bUseUnity = false;
```

**Comment by Edstub207** [comment]
Thanks, @fpwong That looks correct :)

**Comment by fpwong** [comment]
Hi @Edstub207 I believe this is fixed in 4.0.1. Currently the plugin still has PCHs enabled by default. Let me know if there are still more compile issues

**Comment by Skjolnir** [comment]
Hi, the current version does have a few missing includes with PCHs disabled. I've fixed them myself locally, but wanted to make you aware at least.

**Comment by fpwong** [comment]
Hi @Skjolnir, thanks for letting me know. I'll have a look at fixing these for the next update.
