### ISSUE TITLE
Crash: Assertion failed: OwningNode (UE5)

### ISSUE THREAD

**Issue by tshabi8** [fpwong/BlueprintAssistWiki#88]
Have the latest BlueprintAssist:

Assertion failed: OwningNode [File:D:\RocketSync\5.0.0-19505902+++UE5+Release-5.0\Working\Engine\Source\Runtime\Engine\Classes\EdGraph\EdGraphPin.h] [Line: 441]

UnrealEditor_BlueprintAssist!FBAUtils::GetPinPos() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistUtils.cpp:383]
UnrealEditor_BlueprintAssist!FKnotNodeTrack::GetTrackHeight() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\BlueprintAssist\Source\BlueprintAssist\GraphFormatters\KnotTrack\KnotTrack.cpp:97]
UnrealEditor_BlueprintAssist!FKnotTrackCreator::CreateKnotTracks() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\BlueprintAssist\Source\BlueprintAssist\GraphFormatters\KnotTrack\KnotTrackCreator.cpp:181]
UnrealEditor_BlueprintAssist!FKnotTrackCreator::FormatKnotNodes() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\BlueprintAssist\Source\BlueprintAssist\GraphFormatters\KnotTrack\KnotTrackCreator.cpp:41]
UnrealEditor_BlueprintAssist!FEdGraphFormatter::FormatNode() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\BlueprintAssist\Source\BlueprintAssist\GraphFormatters\EdGraphFormatter.cpp:281]
UnrealEditor_BlueprintAssist!FBAGraphHandler::FormatNodes() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistGraphHandler.cpp:2751]
UnrealEditor_BlueprintAssist!FBAGraphHandler::UpdateNodesRequiringFormatting() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistGraphHandler.cpp:2075]
UnrealEditor_BlueprintAssist!FBAGraphHandler::Tick() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistGraphHandler.cpp:474]
UnrealEditor_BlueprintAssist!FBATabHandler::Tick() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistTabHandler.cpp:51]
UnrealEditor_BlueprintAssist!FBAInputProcessor::Tick() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistInputProcessor.cpp:88]
UnrealEditor_Slate!FSlateApplication::FinishedInputThisFrame() [D:\build\++UE5\Sync\Engine\Source\Runtime\Slate\Private\Framework\Application\SlateApplication.cpp:1376]
UnrealEditor!FEngineLoop::Tick() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:5199]
UnrealEditor!GuardedMain() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Launch.cpp:183]
UnrealEditor!GuardedMainWrapper() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:147]
UnrealEditor!LaunchWindowsStartup() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:283]
UnrealEditor!WinMain() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:330]
UnrealEditor!__scrt_common_main_seh() [d:\a01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

**Comment by fpwong** [comment]
Hi tsabi8, I was not able to replicate this exact crash but did replicate a very similar crash. Let me know the latest version (4.0.2) has fixed this for you.

**Comment by craigvc** [comment]
I am getting a similar error when building a map in 5.4.4

**Comment by fpwong** [comment]
Hi @craigvc, sorry about that! Next time this happens could you paste the crash log here (or in a new issue)?

The log above is due to formatting and I'd suspect yours would come from a different source when building your map.
