### ISSUE TITLE
Formatting causes problems with comments

### ISSUE THREAD

**Issue by chozabu** [fpwong/BlueprintAssistWiki#9]
I am using your (brilliant) autosize comments plugin.

I often find (particularly when formatting some older messy BPs) that the comments will reposition incorrectly

Sometimes the reason is mysterious - but there are also situations where the formatting does not leave room for comments to bound correctly, and requires manual repositioning to be able to place a box around a given group of nodes. Usually in a more complex "Sequence" routine.

A possible solution could be for the formatter to format a groups of nodes inside comments first, then treat the comment as a single large block when formatting the rest of the graph.

**Comment by fpwong** [comment]
Hi chozabue, unfortunately I have no plans to fix this issue right now. I did think about the grouping nodes inside comments but it would require a large rework to the formatting algorithm and decided it would take too long to rewrite these parts of the algorithm.

On a side note: the new feature: "format only selected nodes" which will come in the next update may help you. With this, you can select the nodes inside the comment and drag them to a place which doesn't overlap before formatting them.

It's not quite as neat as just pressing the formatting button but for these certain situations it can be a temporary fix.

**Comment by chozabu** [comment]
Hi fpwong, Fair enough - I am not surprised it will take a large re-work

I'll aim to use the full auto formatting setup on new projects, but "format only selected nodes" will be very handy when working on existing projects with large unformatted node graphs (This is how I have used other formatters in the past, but much prefer the results of your formatting)

Thanks for the response, and looking forwards to the update!

**Comment by chozabu** [comment]
Hey @fpwong - I've been making good use of this plugin for the past month - still finding it great - Though generally without autosize comments enabled to avoid issues.

Did you implement a "format selection" I don't see it listed here: https://github.com/fpwong/BlueprintAssistWiki/wiki/Keyboard-Shortcuts

Would still be fantastic to have the system automatically handle comments well - but would be very happy with "format selection" for now

**Comment by fpwong** [comment]
The shortcut for format node selectively is SHIFT + F. On second thoughts I don't know why I named it like that, will probably rename it to format selection next update.

About the auto size comments having issues: do you happen to have the `Use Knot Node Pool` setting on (in BlueprintAssist settings)? If you do have this setting on, you need to turn `Ignore Knot Nodes` on in the AutoSizeComments setting. You'd notice that the comment boxes would resize wronly when you formatted since the containing knot nodes were being reused in the wrong position.

Otherwise could you provide some more details about the issue between the two?

**Comment by chozabu** [comment]
Shift-F works like a charm - thanks :)

as for more detail on issues with comment/formatting
https://i.imgur.com/kPNB0Vk.png is a very simple example - attempting to get the comments here around the upper/lower nodes will usually cause one of the comments to gather all the nodes.

though similar issues usually occur with heavy use of the sequence node, and when I want non-execution nodes to be grouped

**Sequence nodes**

Until now, I've not changed any settings - but having a look at the settings, I see `Use Knot Node Pool ` is set to true even though `Ignore Knot Nodes` is not

I've changed both to `true` and increased the spacing a little, results on formatting a larger graph below

before format: https://i.imgur.com/yeuGyKb.png
after format: https://i.imgur.com/DF0Pf2U.png
manual tidy: https://i.imgur.com/iXSJ2kR.png
format again: https://i.imgur.com/hbmpr7m.png

Note: on the last "format again" screenshot - this issue occurs even after selecting `Ignore Knot Nodes`
I can happily report the issue is avoided by not including the knot nodes, or by disabling `Use Knot Node Pool ` (perhaps this setting should be off by default?)

With this option changed and spacing increased - I am hopeful to not see any more issues in this area - will report back if so

**non-execution nodes**
A fairly simple example:
before format: https://i.imgur.com/zWsJIAr.png
after format: https://i.imgur.com/uItgY5A.png

Sad to say shift-f does not seem functional on a selection of these nodes, the whole macro is formatted - the same seems to happen with any selection of non-execution nodes

**overall**
Thanks for the response! My situation is greatly improved from that setting change and knowing how to use format selection.
Other than treating comments as a node, I'm not sure what would help the `non-execution nodes` issues - I hope the screenshots help you understand my usecase and issues

Thanks again :)

**Comment by fpwong** [comment]
Ah yes I forgot our intial discussion was about the comment boxes and grouping nodes for the algorithm, still no plans to fix that at the moment. Also `Use Knot Node Pool` was certainly meant to be off by default, will need to fix that ASAP.

And I'll have a look into fixing the selective formatting with non-execution nodes.

**Comment by chozabu** [comment]
It's possible that `Use Knot Node Pool` was true from an earlier version - or even that I'm wrong, and have changed the setting, but don't think so.

formatting selection of non-execution nodes will be great - I hope you do develop plans to format groups of nodes in comments sometime, but for now I can simulate it manually with format selection

**Comment by fpwong** [comment]
Hi chozabu, comments are now supported in v2.1.0. Enable the setting 
> Account for comments when formatting
Will close this issue since it is an enhancement. But feel free to make another one if you find any related bugs.
