### ISSUE TITLE
Crash: ContainsGraph doesn't seem to have CommentUnder, and crashes.

### ISSUE THREAD

**Issue by leetNightshade** [fpwong/BlueprintAssistWiki#90]
### EventGraph Crash in BlueprintAssist Version 4.0.4
I got a 100% crash here while using `Shift+F` on some `EventGraph` nodes:

![image](https://user-images.githubusercontent.com/40641737/195223090-eeb5d8ea-cd8e-4dd7-bc96-52c1b9c9b962.png)
---

I'm testing the following changes to at least get around the crash:
![image](https://user-images.githubusercontent.com/40641737/195223153-6caba9e2-f644-478f-9aff-a0ead95eee35.png)

After putting in the above code patch, this is what the middle formatted section looks like after running `Shift+F`, cool works for me:
![image](https://user-images.githubusercontent.com/40641737/195223446-feafc8a6-4c18-45e9-967a-a12d784007fc.png)

From the above, I also ran into a control node overlapping with a Switch/Select. 
![image](https://user-images.githubusercontent.com/40641737/195223664-0a1924ce-61b7-4d4e-9dde-e163267b09ab.png)

**Comment by fpwong** [comment]
Hi @leetNightshade, thanks for reporting this. This fix will be included in the next update.

For the formatting overlap, try selecting the `Select` node and running Refresh Node Sizes `CTRL + SHIFT + R`. The plugin generally is good at detecting when the size of a node changes. But it seems for the select node, when you change the image, it fails to see that the pins are expanding which causes the overlaps. Will try to fix this.

**Comment by fpwong** [comment]
Fixed in 4.0.6.
