### ISSUE TITLE
Hello，When will the version for UE5.1 be released?

### ISSUE THREAD

**Issue by bengmusic02** [fpwong/BlueprintAssistWiki#91]
Hello，When will the version for UE5.1 be released?

**Comment by fpwong** [comment]
Officially I can only release it when 5.1 comes out. If you'd like you can try to compile it yourself following the instructions here: https://github.com/fpwong/BlueprintAssistWiki/wiki/FAQ#building-for-a-non-supported-ue-version

Another user has done this and found a few compile issues on their side but mostly trivial class name changes (check the recent qustion by IntaxQ here https://www.unrealengine.com/marketplace/en-US/product/blueprint-assist/questions). I will try to download the 5.1 preview soon and push an update which fixes these compile issues.

**Comment by bengmusic02** [comment]
Thanks




ben-6
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fpwong/BlueprintAssistWiki"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月13日(星期四) 下午3:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fpwong/BlueprintAssistWiki] Hello，When will the version for UE5.1 be released? (Issue #91)





 
Officially I can only release it when 5.1 comes out. If you'd like you can try to compile it yourself following the instructions here: https://github.com/fpwong/BlueprintAssistWiki/wiki/FAQ#building-for-a-non-supported-ue-version
 
Another user has done this and found a few compile issues on their side but mostly trivial class name changes (check the recent qustion by IntaxQ here https://www.unrealengine.com/marketplace/en-US/product/blueprint-assist/questions). I will try to download the 5.1 preview soon and push an update which fixes these compile issues.

**Comment by fpwong** [comment]
UE5.1 is supported now in plugin version 4.0.9
