### ISSUE TITLE
Strange added reroute node locations

### ISSUE THREAD

**Issue by leetNightshade** [fpwong/BlueprintAssistWiki#93]
While running Shift+F (and Ctrl+Shift+R) on this block, something really weird happens to these reroute nodes:

![image](https://user-images.githubusercontent.com/40641737/198717921-b62243d4-ad77-4404-aa56-89e9b4356b76.png)

**Comment by fpwong** [comment]
Thanks for reporting this, I was able to replicate this issue. This will be fixed in the next update.

**Comment by fpwong** [comment]
This has been fixed in 4.0.7
