### ISSUE TITLE
Right clicking a function in blueprint function list no longer works

### ISSUE THREAD

**Issue by Grimicus** [fpwong/BlueprintAssistWiki#94]
Whenever I right click a function in the blueprint function list, the right click is stolen by the plugin and doesn't perform the choice I picked in the function right click menu.

Repro:
Select a function node within the blueprint.
Right click a function in the function list to the left and choose any option (I typically choose Find References)
See that the choice is not performed and another right click menu appears on top of the function. (related to the node previously selected)
![image](https://user-images.githubusercontent.com/27870686/200241484-0dba172c-67cf-4694-acb9-bf1c5c2b8b22.png)

**Comment by fpwong** [comment]
Hi @Grimicus, sorry I am unable to replicate this issue. I've recorded a video attempting the reproduction, let me know if I am missing anything. 

Tested on UE 5.0.3 | BA 4.0.7

https://streamable.com/t7vsgs

**Comment by Grimicus** [comment]
weird, your repro is what I was doing.  I wonder if it is just a conflict with another one of my plugins :(
