### ISSUE TITLE
Crash in version 4.0.7

### ISSUE THREAD

**Issue by leetNightshade** [fpwong/BlueprintAssistWiki#95]
I hit a crash in version 4.0.7 when running `Shift+F` in a BP EventGraph, from an invalid NodeInfo shared pointer. 

![image](https://user-images.githubusercontent.com/40641737/200444311-a5781994-c769-4381-9ce9-ac1ace70137c.png)

**Comment by leetNightshade** [comment]
3 for 3, I deleted the comment in case that had an effect, and I did the operations in a different order and sorted. Shift+F worked,  up until I added the empty branch. 
![image](https://user-images.githubusercontent.com/40641737/200446508-510286f6-353d-4ca6-a167-a4479b46d946.png)

**Comment by leetNightshade** [comment]
From print debugging, it seems GetFormatXInfo is returning null from a valid node. Just to hold me over until the next version update, I'm using these quick changes. 
![image](https://user-images.githubusercontent.com/40641737/200449380-b4c43c75-aff3-4661-8aa0-ca04c463dc22.png)
![image](https://user-images.githubusercontent.com/40641737/200449455-e0da963c-11ad-40bf-bdfc-4ec282f21bcc.png)

**Comment by fpwong** [comment]
Hi @leetNightshade, sorry about this. Overlooked the selective formatting interaction with this latest update, I will submit a fix for this today.

**Comment by fpwong** [comment]
Let me know if these cases have been fixed in 4.0.8

**Comment by leetNightshade** [comment]
The exact BP that triggered this was already reworked into a function, so I can't be 100% sure this is fixed. But I haven't run into it yet, so maybe? I can close for now. Thank youu! <3
