### ISSUE TITLE
Is there a way to get comments to not overlap? 

### ISSUE THREAD

**Issue by leetNightshade** [fpwong/BlueprintAssistWiki#98]
I'm using both BlueprintAssist and your AutoSizeComments. Is it possible to get comments to not overlap when autoformatting? 

![image](https://user-images.githubusercontent.com/40641737/201202171-9903c88d-0bf7-408e-8641-838e5fe14fe9.png)

Highlighted areas of contention:
![image](https://user-images.githubusercontent.com/40641737/201202249-99373bc6-5b98-425e-a705-505a975a3937.png)

Closeups:
![image](https://user-images.githubusercontent.com/40641737/201202280-f421a6f7-4904-4e76-b8d8-39a30072bcc7.png)
![image](https://user-images.githubusercontent.com/40641737/201202311-f3afae8f-5c46-4a8a-a900-3c5072b7d94a.png)
![image](https://user-images.githubusercontent.com/40641737/201202351-22c087d6-6af1-4a51-8bd5-da450462344a.png)

IMO it's never okay to have separate comments overlap even a little. I notice one of them has a reroute node in two comments: ouch. 

Appreciate any guidance/help on this. 🙏

**Comment by fpwong** [comment]
It looks like you might have the setting `Apply Comment Padding` disabled. This is quite a recent feature so there may be some issues with the algorithm which can cause the comments to overlap. Do post them here if you find any.

**Comment by leetNightshade** [comment]
Perfect, thank you!!
